### ISSUE TITLE
makefile.extensionOutputFolder should not log user paths to telemetry

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-makefile-tools#114]
Before I can enable this telemetry point in our dashboard we need to scrub it like some of the other fields that have PII.  It is currently blocked.  We don't need that data anyway, we just care about whether the setting is used or not.

**Comment by andreeis** [comment]
Also fix the debug/launch string in the configure trigger because it's seen as a path.

**Comment by andreeis** [comment]
When I change the default for extensionOutputFolder I get "...". I can't make it report a path. I wonder how to reproduce this. Do you still see this happening?
