### ISSUE TITLE
Setting to increase the dryrun timeout

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#132]
If for any reason we got the value too small, it's good to give the user the option to set it to higher instead of being annoyed by it. Once clicked it doesn't show up again during that same configure step, but it will show up again during the next configure.

**Comment by gcampbell-msft** [comment]
This is a reasonable idea, but I haven't seen anybody run into an issue here, I think we can close and wait until users hit an issue with this. Suggesting to close.

**Comment by GrumpyMeow** [comment]
I'm trying to start developing on the OpenWrt using VSCode and this extension. 
After 80seconds i get the time-out error...

**Comment by gcampbell-msft** [comment]
@GrumpyMeow Could you create a new issue for this? We'd be very excited to take an open source contribution from you
