### ISSUE TITLE
String setting when the make invocation needs a prepend command

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#135]
Opening this as low priority item, as it is very probable that we would not implement it.
Some developers need to invoke make via some other tools (example: "wsl -e make" and others, not wsl related). Currently, they've been including such commands in the makePath setting, which kind of works but it can be easily broken because the extension treats makePath as a path.
We can implement a new setting, that would prepend its value to makePath when we configure or build.
There is a good workaround, to include the command in a wrapper script and point "makefile.makePath" to it.
Before implementing anything, we'll wait and see how often this is needed and if the workaround is acceptable.

**Comment by andreeis** [comment]
Another scenario where this is needed is when the system language is not english. The extension needs to parse english output from "make". Until we implement a fix for this, the users can invoke a script via "makefile.makePath": 
"$ LANGUAGE=en_US make"

**Comment by gcampbell-msft** [comment]
This is related to #152, I think, based on how long this has been open, we can close. However, it does seem like there could be a use case for a wrapper script or something, but it seems like the workarounds have been. 

Suggesting to close.

**Comment by andreeis** [comment]
Can close. I even forgot that I had opened an issue about producing english output when the system is set on a language. Actually this is done already from the code of the extension. We have a boolean and a few different triggers for it and we estimate whether we honor or ignore the locale setting. Good to close.
