### ISSUE TITLE
Build fails on paths with spaces

### ISSUE THREAD

**Issue by ftrias-pole3** [microsoft/vscode-makefile-tools#138]
When using a makefile where the path has spaces, the build command fails. I am using a custom Makefile Path and Make Path. It appears that the "make" command (which also has space) is quoted properly and executes, but the "makefile" path is not. See below.

Building the current target. Command: C:\Program Files (x86)\Microchip\MPLABX\v5.35\gnuBins\GnuWin64\bin\make.exe -f c:\Users\My Name\Documents\Source\Makefile.vscode
make: c:\Users\My: No such file or directory
make: *** No rule to make target 'c:\Users\My'.  Stop.
Target  failed to build.

**Comment by andreeis** [comment]
Thank you for opening this report. We will fix this for the upcoming patch release. I wasn't able to use escaped quotes either, the extension would do other wrong stuff in that scenario.
As a workaround, you can produce a full clean build log in your terminal, then point the extension to that file via the setting "makefile.buildLog" in .vscode/settings.json.

**Comment by andreeis** [comment]
@ftrias-pole3, until we release Makefile Tools 0.2.1, you can install a vsix from https://github.com/microsoft/vscode-makefile-tools/actions/runs/793552744 with a fix for this problem.
