### ISSUE TITLE
Broke intellisense with ccache

### ISSUE THREAD

**Issue by jardinimf** [microsoft/vscode-makefile-tools#140]
If the gcc is aliased to ccache or the $(CC) expands to "$(CCACHE) $(GCC) ..." then intellisense was unable to find the default C/C++ headers.

Partial solution for ccache in $(CC) expansion was add an makefile.configurations to undefine $(CCACHE), but with side effect of making build slow.

Can it be possible to add configurations for dry-run only? Or someone have a tutorial on how to configure vscode-makefile-tools for use with ccache?

Thank you.

**Comment by andreeis** [comment]
Thank you for opening this report. We didn't test this with CCache over here yet but there are in place some things that I hoped it would enable easily this scenario.
The idea with dry-run only configurations is a good one and once we figure out how to unblock you with using CCache with Makefile Tools we'll look at where that feature request fits in our backlog.

Set the logging verbosity to debug ("makefile.loggingLevel": "Debug"), make the extension dump the logging in a file ("makefile.extensionLog": ".vscode/extension.log"), reload your project and let it configure.

Then share with us .vscode\dryrun.log and .vscode\extension.log.

In the meantime, as a workaround you can produce yourself a full clean build log that you can point the extension to with "makefile.buildLog". And do any text processing operations that seem to help the extension parse it. Replace CCACHE with nothing or....
When a buildLog is defined, the extension will not invoke make when parsing for IntelliSense. I imagine all should work for you this way. Just make sure that you always have an up to date build log that accurately represents what state of the project you wish to work on.

You can produce this build log by running your usual make build command in any of your development terminals or you can still use the extension for that. Explore the Makefile Tools build commands in the palette. "Makefile: Build clean the target ALL" or "Makefile: Build clean the current target". The output of the build is dumped in the "Makefile Tools" output channel or in the extension.log that you set with "makefile.extensionLog".

**Comment by jardinimf** [comment]
Did the log collect, it was easy to see the issue in the extension.log

Taking one line as example:

    ...
    Force Includes: 
    Standard: c11
    IntelliSense Mode: gcc-x64
    Compiler Path: /usr/bin/ccache
    ...

Because of ccache the "Compiler Path: " get the wrong hint for the path

After a short test without ccache, it got the correct path:

    ...
    Force Includes: 
    Standard: c11
    IntelliSense Mode: gcc-x64
    Compiler Path: /opt/Nuclei/gcc/bin/riscv-nuclei-elf-gcc
    ...

[dryrun.log](https://github.com/microsoft/vscode-makefile-tools/files/6152344/dryrun.log)
[extension.log](https://github.com/microsoft/vscode-makefile-tools/files/6152345/extension.log)

**Comment by andreeis** [comment]
Wonderful, thank you. We will fix this. In the mean time, don't use a workaround that is not using ccache to get your builds slow, use "makefile.buildLog" to point to a full clean build output created by you separately, after you remove all occurences of "/usr/bin/ccache". IntelliSense parsing will not invoke "make" nor "ccache" but will always read from that log. All features of the extension should still fully work. Just that if you make a build change (new file, remove file, new flags, etc...) you would have to redo the build log to have up to date information.

**Comment by andreeis** [comment]
@jardinimf, until we release Makefile Tools 0.2.1, you can install a vsix from https://github.com/microsoft/vscode-makefile-tools/actions/runs/793552744 and get ccache support.
