### ISSUE TITLE
makefile not found in the settings -> extensions

### ISSUE THREAD

**Issue by drimmeer** [microsoft/vscode-makefile-tools#145]
I installed the makefile extension according to https://devblogs.microsoft.com/cppblog/now-announcing-makefile-support-in-visual-studio-code/ , but when I tried to following instruction in section "Configuring your project" to try to go to File > Preferences > Settings -> Extensions, I could not find the 'makefile' as stated in this section.

Please advice.

**Comment by bobbrow** [comment]
Can you help us understand better what you mean when you say that you cannot find the makefile?  If you open a folder and the makefile is not in the root of that folder, you will need to set the `makefile.makefilePath` setting to tell us which makefile you'd like to use.  Then you can run the `Makefile: Configure` command to get started.

**Comment by drimmeer** [comment]
Hi,
Thank you for your prompt response.

As described in the ticket, I meant that I could not find the 'makefile' option under the 'extension' session of the 'settings' page. That is, I don't know where to specify this 'makefile.makefilePath ', is it in a file? where is the file?

Thanks,
Jamie

________________________________

**Comment by bobbrow** [comment]
To edit settings, go to File -> Preferences -> Settings
![image](https://user-images.githubusercontent.com/12818240/114768322-8cfdfc80-9d1d-11eb-8ad7-9831f2f32df5.png)

When the UI appears, you can type 'makefilepath' in the search and it should appear.  (`makefile.makefilePath` is the name of the setting as it appears in JSON)
![image](https://user-images.githubusercontent.com/12818240/114768431-ae5ee880-9d1d-11eb-8700-971320a3a2c2.png)

**Comment by drimmeer** [comment]
Wow! Your trick worked! Now the 'makefile' option appears! Thank you very much!

**Comment by bobbrow** [comment]
Glad we could help!
