### ISSUE TITLE
Debugger Configuration to Enable Pretty Printing GDB

### ISSUE THREAD

**Issue by Johnny-Geng** [microsoft/vscode-makefile-tools#148]
Hi there, I'm a novice programmer, and I just wonder if there is a way to change the default configuration for makefile tool to enable pretty printing when debugging (so that I can inspect elements in vectors, strings, etc. (from STL) properly, instead of getting a bunch of memory address )?

I know that whenever I debug without the makefile tool, I'm able to achieve so by putting the following code in the launch.json configuration:
`            "setupCommands": [{ 
                "description": "Enable pretty-printing for gdb",
                "text": "-enable-pretty-printing",
                "ignoreFailures": true
`
But I'm not sure how to do it with the makefile tool. I tried putting this snippet of code into the"makefile.launchConfigurations" [] section, but it didn't appear to work.

**Comment by andreeis** [comment]
We did not implement yet a way for Makefile Tools to pass such requirements to the debugger. We will address this feature request by following the example of CMake Tools (which adds information like this via the "cmake.debugConfig" setting).

Until then, you can use launch.json (and debugging via F5) which supports this syntax and to take advantage of Makefile Tools in such scenario you can use commands like:
         "program": "${command:makefile.launchTargetPath}", ==> this also triggers a build of the current target. If you want no build to be automatically spawned, use getLaunchTargetPath. This returns full path to executable.
         "args": ["${command:makefile.getLaunchTargetArgsConcat}"],  ==> no build triggered
         "cwd": "${command:makefile.getLaunchTargetDirectory}",  ==> no build triggered

There is no "without get" equivalents for getLaunchTargetArgs(Concat) and getLaunchTargetDirectory.
There is also an additional command (getLaunchTargetFileName and launchTargetFileName) that can be used in combination with getLaunchTargetDirectory and it returns the file name (no extension).
