### ISSUE TITLE
Preconfigure arguments

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#151]
Implement a new string (or string array) setting "preConfigureArgs" to be passed to the preconfigure script when it is run.
Global ("makefile.preConfigureArgs") and per configuration ("makefile.configurations[].preConfigureArgs").
The current workaround is to wrap a different script on top of the desired one, with the arguments written in the wrapper. This can quickly explode to many configuration scripts and wrappers, while it can be cleanly solved from the settings with a single preconfigure script.

**Comment by andreeis** [comment]
This would be different than https://github.com/microsoft/vscode-makefile-tools/issues/144 and similar in implementation with https://github.com/microsoft/vscode-makefile-tools/issues/122.

**Comment by 156898293** [comment]
Is "makefile.preConfigureArgs" supposed to work in pre-release v0.8.16 (vscode 1.84.2)?
Because it is not.
Feel free to ignore this comment, its just a friendly notification.

**Comment by 156898293** [comment]
ok, will create a bug report

**Comment by gcampbell-msft** [comment]
Assuming I'm right, I think I know your issue. Would this fix it? #530

**Comment by 156898293** [comment]
> Assuming I'm right, I think I know your issue. Would this fix it? #530
I don't think so... I created #531
If you need we can do a debug session over teams.
