### ISSUE TITLE
Implement a command prefix for the make invocation

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#152]
In scenarios like https://github.com/microsoft/vscode-makefile-tools/issues/134 or https://github.com/microsoft/vscode-makefile-tools/issues/126, users may need to inject something in the same command that calls for make: either set a variable (although this can be done with preconfigure as well and in future with env var settings) or call various wrapper tools.

Currently some inventive users are hacking "makefile.makePath" for something like this (add the prefix in the setting itself or repurposing makePath to a wrapper script).

It would be useful to have a "makefile.makePrefix" and "makefile.configurations[].makePrefix" to help for the various complex and interesting scenarios out there.

**Comment by gcampbell-msft** [comment]
To me, this feels like a mis-use of the make invocation and we should suggest users to use the pre-configure script. Suggesting to close.

**Comment by andreeis** [comment]
Agree to close because I read again issues 126 and 134 and both have support available now which wasn't then or better recommended alternatives. Also, preConfigure effects persist for configure and build. I wonder if we ever need different env vars for these two scenarios, in which case we can still offer something else than a prefix.
