### ISSUE TITLE
Using "integratedTerminal" instead of Debug Console?

### ISSUE THREAD

**Issue by MarcusOy** [microsoft/vscode-makefile-tools#157]
It seems like there is no documented way to use the "integratedTerminal" while debugging instead of the Debug Console. I am trying to debug a C++ ncurses app, where a terminal must be present for the app to run. Since this extension doesn't seem to use `launch.json` (and rather keeps its launch config in `settings.json` under `"makefile.launchConfigurations": [...]`), we cannot set `"console": "integratedTerminal"`.

**Comment by andreeis** [comment]
Thank you for opening this report. In the future we will add more things to "makefile.launchConfigurations" (including console types). But you can use launch.json now with this extension. It can make use of the extension knowledge with the following commands that are available: getLaunchTargetPath, getLaunchTargetDirectory, getLaunchTargeFileName, getLaunchTargetArgs, getLaunchargeArgsConcat, launchTargetPath (same as getLaunchTargetPath but triggers a build), launchTargetFileName (same as getLaunchTargeName but triggers a build).

Here is an example of how to use these commands in launch.json:
         "program": "${command:makefile.launchTargetPath}",
         "args": ["${command:makefile.launchTargetArgsConcat}"],
         "cwd": "${command:makefile.launchTargetDirectory}",

Let us know how this works.

**Comment by gcampbell-msft** [comment]
Hi @MarcusOy, could you confirm that your issue is resolved? 

If we don't hear from you, we plan to close this issue. Thanks!

**Comment by andreeis** [comment]
@MarcusOy , more specifically, is the launch.json workaround unblocking you?
Otherwise, what I mentioned that we will add more things into launchConfigurations setting we didn't get to yet. And here is the work item tracking some parity between "makefile.launchConfigurations" and launch.json: https://github.com/microsoft/vscode-makefile-tools/issues/382
