### ISSUE TITLE
Better wording in logs, commands, tooltips, etc...

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#164]
For a future cleanup, evaluate the names of commands, text in logs, tooltips in UI, etc...
Some suggestions about the build commands: https://github.com/microsoft/vscode-makefile-tools/issues/136. 
Add more as we think of improvements or we receive suggestions from the community.

**Comment by gcampbell-msft** [comment]
Based on the item linked #136, this is fixed, and I think we can simply continually evaluate this as we implement features. Closing.
