### ISSUE TITLE
Update 0.2.1 appears to break finding standard headers with gcc-arm-none-eabi

### ISSUE THREAD

**Issue by dueringa** [microsoft/vscode-makefile-tools#165]
Since I updated Makefile Tools to version 0.2.1 (from 0.2.0 if I think), suddenly, I get IntelliSense warnings about stdint.h and stdbool.h not found. The project compiles fine, though.

This is with a configuratuin using gcc-arm-none-eabi.

The "error squiggles" were not present in the previous version.

This is my `c_cpp_properties.json`:

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:/SysGCC/arm-eabi-latest/bin/arm-none-eabi-gcc.exe",
            "cStandard": "gnu11",
            "cppStandard": "gnu++11",
            "intelliSenseMode": "windows-gcc-arm",
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ],
    "version": 4
}
```

dryrun.log and extension log:

[dryrun.log](https://github.com/microsoft/vscode-makefile-tools/files/6440815/dryrun.log)
[mktool.log](https://github.com/microsoft/vscode-makefile-tools/files/6440816/mktool.log)

Not sure if this is related to #140  - I'm not using ccache, though

**Comment by dueringa** [comment]
For completeness, inc/config.h:

```
#pragma once

#include <stdint.h>

typedef uint32_t error_t;
```

src/main.c:

```
#include "config.h"

int main(void)
{
  while(1);
}
```

This is just to demostrate that stdint.h is not found according to IntelliSense

**Comment by andreeis** [comment]
No need for you to downgrade to 0.2.0 to give us the old logs. I loaded your dryrun.log as a build log myself, to parse exactly on that output and I found the diffs between the extensions.

Are you using MinGW or MSYS environment?
If so, one set of diffs is that the compiler and source file paths changed from posix to windows style and also compiler path is full path now. I need to see the C/C++ two logs that I asked above to see if CppTools uses the posix or the windows path.

The most probable culprit is that we made a fix in 0.2.1 regarding parsing compiler arguments and I see in your case we parse werror wrong. I'll fix that asap and send you a private vsix to install to see if it unblocks you.

**Comment by dueringa** [comment]
Sorry for the delay, please find attached the output of the log, and C/C++ diagnostics

[output.txt](https://github.com/microsoft/vscode-makefile-tools/files/6445941/output.txt)

> Are you using MinGW or MSYS environment?

I'd say neither? I have MSYS2 installed, but I'm not using it in this case.

What strikes me is the

```
 Unable to resolve configuration with compilerPath "C:/SysGCC/arm-eabi-latest//bin/arm-none-eabi-gcc.exe".  Using "cl.exe" instead.
```

error message.

**Comment by dueringa** [comment]
This indeed fixes the problem. IntelliSense doesn't display errors anymore.

Thanks 👍

**Comment by muhammadelmogy** [comment]
To whom ever comes here and could not fix his issue with the suggested solution, I followed those steps over here and it helped:
[IntelliSense for cross-compiling](https://code.visualstudio.com/docs/cpp/configure-intellisense-crosscompilation)
