### ISSUE TITLE
Pre-configure script is broken on Linux

### ISSUE THREAD

**Issue by avrahamshukron** [microsoft/vscode-makefile-tools#170]
Commit a157d1aae00340ea2e050443b151a7900aa87f94 introduced a bug:

```ts
scriptArgs.push(`"source '${wrapScriptFile}"'`);
```

Notice how the single quotes meant to be around `${wrapScriptFile}` are actually crossing the double-quotes boundaries, so the source command contains stray `"` and the invocation fails.

**Comment by andreeis** [comment]
Thank you for letting us know. We will fix it immediately and we'll release a patch update 0.2.3.
