### ISSUE TITLE
Implement util.looksLikePath

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#186]
Implementing this helper to identify if a string looks like a valid path or not (without checking the file system) will help with cleaning up some conditions in parser.ts and with testing which now needs to save lots of 0 bytes files only to pass this check.
We check now for fs.exists on directories or files because we didn't implement something else to tell the difference when a tool we are interested to parse it out from a line (with invocation and arguments) is prefixed by random text (and we should reject the match) versus a path (and we should keep the regexp match).

**Comment by gcampbell-msft** [comment]
Testing enhancement, I'm not sure how much this is necessary, so I would say we could likely close this, however, I don't feel strongly about that as it's likely a small change, so I'll not add suggest-to-close for now.

**Comment by andreeis** [comment]
Agree this can be closed.
