### ISSUE TITLE
GDB not stopping on breakpoint and not showing line number in WSL Ubuntu 20.04

### ISSUE THREAD

**Issue by pdecherf** [microsoft/vscode-makefile-tools#188]
Hello, GDB is not working in my workspace. It has been working in other workspace before and I don't know what make it different this time. Here is what gdb says :

=thread-group-added,id="i1"
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
**Warning: Debuggee TargetArchitecture not detected, assuming x86_64.**
=cmd-param-changed,param="pagination",value="off"
Stopped due to shared library event (no libraries added or removed)
Loaded '/lib64/ld-linux-x86-64.so.2'. Symbols loaded.

Breakpoint 1, 0x000000000801d642 in main ()
Loaded '/lib/x86_64-linux-gnu/libstdc++.so.6'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libgcc_s.so.1'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libc.so.6'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libm.so.6'. Symbols loaded.

I've seen other issues on vs code concerning this line "Warning: Debuggee TargetArchitecture not detected, assuming x86_64".
Using the debugger from the C/C++ extension doesn't work either, it produce the same output, except if I provide "targetArchitecture": "x86_64", in lauch.json, which produce the same output without the line "Warning: Debuggee TargetArchitecture not detected, assuming x86_64".
I saw this advice here https://github.com/microsoft/vscode-cpptools/issues/2376#issuecomment-546301762 and it look like it solved the problem which is not the case here

Let me know if you need any additional information

**Comment by andreeis** [comment]
@pdecherf, we are investigating this. Not very likely, but does setting "makefile.defaultLaunchConfiguration.stopAtEntry": "true" in your .vscode/settings.json help at least with stopping at the beginning (the entry point) of your program?

@WardenGnaw, any ideas? There is also a repro at duplicate issue https://github.com/microsoft/vscode-makefile-tools/issues/189 which I will try soon.

**Comment by andreeis** [comment]
@pdecherf, can you add the following in your launch.json and send to us the content of the debug tab? This may provide clues for why the breakpoint doesn't bind.

“logging”: {
   “engineLogging”: true,
   “traceResponse”: true
}

**Comment by andreeis** [comment]
Are you able to share your project?

**Comment by andreeis** [comment]
I just investigated the repro for 189 and that project was setup to add debug switches after the non debug -O3. As soon as I removed -O3 from the makefile I was able to debug properly. I am mentioning just in case this may happen in your project. Double check the command line compiling the source code of where you're trying to debug.

**Comment by pdecherf** [comment]
This last message gave me the idea to look back at my Makefile and I realized there was a mistake on my side. Sorry about that, everything works fine now.

**Comment by andreeis** [comment]
Glad to hear, closing the issue.
