### ISSUE TITLE
Include errors for generated headers in MicroPython

### ISSUE THREAD

**Issue by cdwilson** [microsoft/vscode-makefile-tools#192]
It looks like Makefile Tools is not finding some generated headers when used with the MicroPython project:

![image](https://user-images.githubusercontent.com/14631/123534510-75a29e80-d6d2-11eb-9b53-2dcfd84c72d7.png)

I followed the suggested instructions from https://github.com/microsoft/vscode-makefile-tools/blob/main/docs/repositories.md and set up a top-level Makefile to build the STM32 port:

```
all:
	$(MAKE) -C ./mpy-cross
	$(MAKE) submodules -C ./ports/stm32
	$(MAKE) -C ./ports/stm32
```

Then, I set the build target to `all` and ran the build:

![image](https://user-images.githubusercontent.com/14631/123534117-a2a18200-d6cf-11eb-8e80-4e61e95b90f1.png)

When I open `ports/stm32/pin.h`, I see red squiggles under `#include "genhdr/pins.h"`.

Here's my `settings.json`:

```
{
    "makefile.extensionOutputFolder": "./.vscode",
    "makefile.configurations": [
        {
            "name": "PYBv1.1",
            "makeArgs": [
                "BOARD=PYBV11"
            ]
        }
    ]
}
```

**Comment by andreeis** [comment]
@cdwilson, is the generated header present on disk at that location, meaning there was a full build performed before loading the project in VSCode and activating the Makefile Tools extension? If not, do a build and try again.
If it's present, then let's see how the extension parses the include folders. Set "makefile.loggingLevel" to "Debug" and "makefile.extensionLog" to ".vscode/extension.log" in your .vscode/settings.json, load your project again in VSCode, let it configure (or run the configure command yourself -"makefile.configure" or "makefile.cleanConfigure"- from the palette) and share with us the following files: .vscode/dryrun.log and .vscode/extension.log.

**Comment by cdwilson** [comment]
@andreeis my mistake, I didn't realize that the configure step needed to be run manually after the build.  Things started working (squiggle went away) after running `makefile.configure` in the palette.  I think this is simply due to the fact that `genhdr/pins.h` is created during the build, so it wasn't found during the initial configure.  Thanks for pointing me in the right direction!

**Comment by andreeis** [comment]
@cdwilson,  glad to hear.
