### ISSUE TITLE
Cannot build a file

### ISSUE THREAD

**Issue by victoria-georgieva** [microsoft/vscode-makefile-tools#195]
The project needs to configure in order to build properly the current target.
Saving opened files before build.
Generating configuration cache with command: make.exe -f "C:\Users\Victoria Georgieva\Documents\GitHub\parallel-sudoku-solver\src\Makefile" --dry-run --keep-going --print-directory
Writing the dry-run output: c:\Users\Victoria Georgieva\Documents\GitHub\parallel-sudoku-solver\.vscode\dryrun.log
Generating dry-run elapsed time: 0.04
The make dry-run command failed.
IntelliSense may work only partially or not at all.
'"make.exe"' is not recognized as an internal or external command,
operable program or batch file.

You can see the detailed dry-run output at c:\Users\Victoria Georgieva\Documents\GitHub\parallel-sudoku-solver\.vscode\dryrun.log
Make sure that the extension is invoking the same make command as in your development prompt environment.
You may need to define or tweak a custom makefile configuration in settings via 'makefile.configurations' like described here: [link]
Also make sure your code base does not have any known issues with the dry-run switches used by this extension (makefile.dryrunSwitches).
If you are not able to fix the dry-run, open a GitHub issue in Makefile Tools repo: https://github.com/microsoft/vscode-makefile-tools/issues
Preprocessing: "c:\Users\Victoria Georgieva\Documents\GitHub\parallel-sudoku-solver\.vscode\dryrun.log"
Configure succeeded.
Configure elapsed time: 0.043
Building target "clean" with command: "make.exe clean -f "C:\Users\Victoria Georgieva\Documents\GitHub\parallel-sudoku-solver\src\Makefile""
'"make.exe"' is not recognized as an internal or external command,
operable program or batch file.
Target clean failed to build.
Building target "" with command: "make.exe -f "C:\Users\Victoria Georgieva\Documents\GitHub\parallel-sudoku-solver\src\Makefile""
'"make.exe"' is not recognized as an internal or external command,
operable program or batch file.
Target  failed to build.

I am trying to run a project from github on the GPU. I have the makefile tools extension installed. Please help with the error

**Comment by andreeis** [comment]
@victoria-georgieva, it looks like the extension doesn't know how to find make.exe. You can either open your VSCode from a command prompt that has make.exe on the path, or you can define "makefile.makePath" in the .vscode/settings.json of your project. Let us know how this works for you.
