### ISSUE TITLE
how to debug a program started by another program

### ISSUE THREAD

**Issue by Edouard59** [microsoft/vscode-makefile-tools#202]
Hello,

I have a program (say app2) which is built using makefiles in VS code with the extension. Once the program is built, this app2 should not be run directly, but another program (say app1) is in charge of starting it. So I have created the following configuration, which starts app1 providing the path on the command line where app2 is located as this is how app1 expects it to be:
`
"makefile.launchConfigurations": [
        {
            "cwd": "/home/app2/",
            "binaryPath": "/home/app1",
            "binaryArgs": ["/home/app2/bin/app2],
            "symbolSearchPath": "/home/app2/bin"
        }
`

I can run the program, and start a debug session. However, when I try to set a breakpoint in some of my app2 code, I see the breakpoint being hit in the debug console:
`
Thread 1 "app1" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff78a13bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7fffffffd340, rem=rem@entry=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
[Switching to thread 15 (Thread 0x7fffcd7fa700 (LWP 63996))](running)
=thread-selected,id="15"
`

But then I cannot step or anything in the code, the breakpoint goes greyedout and if I hover it it says 
`
Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained.
`

Any idea how I can get it to work ?

Thanks

**Comment by bobbrow** [comment]
@WardenGnaw Do we have a guide for setting up child process debugging in VS Code?  It looks like this is linux and I'm assuming gdb.

@Edouard59, without child process debugging, you would need to set up an "attach" configuration in `launch.json` that would attach to app2 after it has launched.

**Comment by WardenGnaw** [comment]
In the `launch.json`, you can add to your configuration:
```
"setupCommands":
{ 
   "text": "-gdb-set follow-fork-mode child", 
   "ignoreFailures": true 
}
```

See [Forks](https://sourceware.org/gdb/onlinedocs/gdb/Forks.html#:~:text=By%20default%2C%20when%20a%20program,set%20follow%2Dfork%2Dmode%20.&text=Set%20the%20debugger%20response%20to%20a%20program%20call%20of%20fork%20or%20vfork%20.) for how you can configure fork/exec modes.

**Comment by Edouard59** [comment]
@bobbrow Yes, this is linux and gdb. It supports child process debugging, and what @WardenGnaw suggested works ! :) I then need to use the vs code "run and debug" panel and I guess cannot use the "debug" or "run in terminal" buttons at the top of the makefile extension panel then but this is no big deal...

@WardenGnaw Thanks for the tip, this makes it work. But when I click on the "stop" button from the debugger, my app1 program continues running... By any luck, do you know of a trick to kill app1 when the debugger is stopped ? I thought maybe the "-gdb-set detach-on-fork off" option would do the trick, but when I enable it, then it doesn't work anymore, I see the processes listed as "running" in the call stack window, but nothing happens, as if they were actually not running...

Thank you for your help,

Edouard

**Comment by Edouard59** [comment]
@WardenGnaw I don't know if it is the clean way of doing it but I managed to kill the app after debugging by adding a "postDebugTask" which runs a pkill command

I'm just not quite sure what this makefile extension brings in the end, as I am not using it for debugging, I have a prelaunch task which calls "make all" to build before debug... So I'm not really using much from this extension, am I ? Maybe the only use left is in configuring the vscode intellisense engine from the makefile info ? (which is still very valuable I don't deny it...)

**Comment by andreeis** [comment]
@Edouard59, putting the quick debug Makefile Tools feature aside, you can still benefit of the following:
- IntelliSense (as you say, it is indeed the major benefit)
- build without switching to your development command prompt and typing the command every time
- launch in terminal (non debug)
- even for debug, when you use launch.json, you can access Makefile Tools commands that let you not hard code various information that the extension can deduce for you. Take a look at [this settings document](https://github.com/microsoft/vscode-makefile-tools/blob/main/docs/makefile-settings.md).

Regarding the post debug task, I can't comment on that yet as I'm still brainstorming and researching.
