### ISSUE TITLE
makefile tools not sending config for files after finding build command

### ISSUE THREAD

**Issue by prsullivan** [microsoft/vscode-makefile-tools#203]
I am trying to use the makefile tools extension as a configuration provider for a makefile project generated by eclipse cdt based environment.

I can see in the extension log that compiler commands are found for my source files but configuration is not sent to cpptools for any source files other than main. It also appears include paths from the command line are also not parsed or added to the configuration.

[https://github.com/prsullivan/demo-for-makefile-tools](https://github.com/prsullivan/demo-for-makefile-tools)

[dryrun.log](https://github.com/microsoft/vscode-makefile-tools/files/7022211/dryrun.log)
[cpptools.log](https://github.com/microsoft/vscode-makefile-tools/files/7022212/cpptools.log)
[extension.log](https://github.com/microsoft/vscode-makefile-tools/files/7022210/extension.log)

**Comment by bobbrow** [comment]
Thanks for the info.  I am able to reproduce the problem and figured out one of the issues.  I'll send a PR for it, but there is still more to investigate and my engineer who works on this is on leave for another 2 weeks.

**Comment by andreeis** [comment]
@prsullivan, we fixed this in the upcoming Makefile Tools 0.3. While we wrap up the release, you can test if you want a vsix from [this link](https://github.com/microsoft/vscode-makefile-tools/actions/runs/1468495870)  (extensions tab --> context menu of "..." in the upper right corner --> install from vsix).

**Comment by prsullivan** [comment]
Thank you for looking this issue! This appears to be solved in the vsix linked above.

**Comment by andreeis** [comment]
@prsullivan, we released Makefile Tools 0.3.0 today which includes a bug fix for this problem. Let us know if you encounter any other issues.

If you would like, you can also leave us a review on [Market Place](https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools&ssr=false#review-details).
