### ISSUE TITLE
makefile.launchConfigurations duplicates launch.json?

### ISSUE THREAD

**Issue by robaol** [microsoft/vscode-makefile-tools#206]
I was using the vscode builtin debugger before I installed the makefile-tools extension and so I had followed the guidance and defined launch/debug definitions in launch.json, which I recall vscode pre-populated for me to some extent.

It would seem to make sense for makefile tool to share/use the same mechanism and files for its launch target? Rather than defining an apparent duplicate ? Or maybe it should be spotting launch.json but isnt?

**Comment by robaol** [comment]
Fair enough. (Note that it appears that the main debugger uses launch.json, not tasks.json, if that makes any difference.

**Comment by bobbrow** [comment]
Haha, sorry, I misspoke.  I substitute `tasks` for `launch` all the time for some reason.

**Comment by andreeis** [comment]
@robaol, also I want to make sure that you know of the Makefile Tools commands that are available for you if you go the launch.json route. Check out [this doc](https://github.com/microsoft/vscode-makefile-tools/blob/main/docs/makefile-settings.md).

**Comment by robaol** [comment]
@andreeis Thank you.
I had a look at the link you provided. I think this is saying that the Makefile Tools extension can define a number of variables which can be referenced from launch.json or tasks.json? (Noting that some of the paths are "smart" and can cause side-effects such as a rebuild as noted on the page.)
On balance, i think i will stick with the launch.json route for debugging. It was part of the vs-code getting started instructions for debugging, I have it set up and if I have non-Makefiles projects as well, then mixing the 2 methods on different projects might become confusing.
I found the descriptions for the launch.json debugging quite ok to follow

Regards
Rob

**Comment by andreeis** [comment]
@robaol, sounds good. Whenever you see you end up duplicating project specific information in your launch/tasks json (like target name) or when it changes often depending on what flavor of your project you currently build (like a specific subdirectory of the build directory) that will be the time to check that document again and you will see that these variables can be very useful.
