### ISSUE TITLE
The table at docs/repositories.md is not very readable on the web

### ISSUE THREAD

**Issue by robaol** [microsoft/vscode-makefile-tools#207]
The table is very tall and wide but the only (horizontal) scroll bar is right at the bottom of the table, at which point the row you are interested in is probably no longer visible, nor are the column headings.

This is possibly/probably? a github issue not a repo one, but is it possible make the page more readable? Maybe by adding scrollbars within the doc frame and freezing the top row and first column?

I tried viewing the raw md, the less said, the better :)

**Comment by andreeis** [comment]
Thank you @robaol for pointing that out. We will explore what we can do to improve this experience.
