### ISSUE TITLE
Help with starting debugging

### ISSUE THREAD

**Issue by Lullabi** [microsoft/vscode-makefile-tools#210]
Hello. I am a CS student and have recently been trying to get this extension to work to better support debugging as I use a lot of makefile projects. However, I've had a lot of issues trying to start debugging. I've set up the tool and when I run without debugging, it works perfectly fine, but when trying to debug, it doesn't work at all.

My makefile settings.json:
`{
    
"remote.SSH.remotePlatform": {
        "hydra19.eecs.utk.edu": "linux"
    },

    "makefile.defaultLaunchConfiguration": {
        "cwd": "/home/ahervey/cs302/cs302/proj2/",
        "binaryPath": "/home/ahervey/cs302/cs302/proj2/volsort",
        "binaryArgs": ["-m merge -n < input"]
    }
}`

I am using a default configuration and build it using make all. The command is supposed to run on the command line as `./volsort -m merge < mini-input`. When I run it without debugging the program runs fine. When I try to debug I get the usage error built into my code:
usage: volsort
    -m MODE   Sorting mode (oblivious, stl, qsort, merge, quick)
    -n        Perform numerical ordering

Any help on what I am doing wrong or how I could get this started would be very helpful. If you need me to submit anything else, please let me know. Thank you!

**Comment by bobbrow** [comment]
Can you try splitting the `binaryArgs` into individual strings?  If you set it like that, I believe you will get a large quoted string (e.g. single argument) sent.

Like this:
```
"binaryArgs": ["-m", "merge", "-n", "<", "input"]
```

**Comment by Lullabi** [comment]
This worked for me. Thank you so much for your help

**Comment by bobbrow** [comment]
Glad to hear that worked for you.  We hope you are enjoying the extension and if you have a chance and could [leave us a review](https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools&ssr=false#review-details), it would help us out.  Thank you.
