### ISSUE TITLE
Unable to open 'futex-internal.h' while debuging

### ISSUE THREAD

**Issue by DoubleLT** [microsoft/vscode-makefile-tools#213]
Hi, thanks to this makefile-tools, my project runs well for release version.

When I try to debug the program, the following error message shows:
```
Unable to open 'futex-internal.h': Unable to read file 'vscode-remote://wsl+ubuntu-20.04/build/glibc-eX1tMB/glibc-2.31/sysdeps/nptl/futex-internal.h' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu-20.04/build/glibc-eX1tMB/glibc-2.31/sysdeps/nptl/futex-internal.h').
```

I have tried to install glibc-source, however, it seems no effect.

Any idea is welcome and thanks in advance.

**Comment by bobbrow** [comment]
Are you seeing this when you press the "pause" button, or when a breakpoint is hit?  I believe this is a known issue with debugging and is outside of this extension.  See: https://github.com/microsoft/vscode-cpptools/issues/2762
It is safe to ignore these messages. You should be able to switch to different frames in the call stack and get to the code you want.

We're glad to hear everything else is working well for you.  If you have a moment and feel like leaving us a [star rating or a review](https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools&ssr=false#review-details), we would appreciate it.

**Comment by bobbrow** [comment]
As regards the URI in that message, that might be something to ask in [a new issue for the cpptools extension](https://github.com/microsoft/vscode-cpptools/issues/new/choose).  I'm not sure how they would do the source file mapping with that type of URI.  Do you have the sources for glibc on that remote machine?

**Comment by wjliuplusplus** [comment]
Many thanks and I'll keep tracking the URL.

**Comment by gcampbell-msft** [comment]
@DoubleLT Due to the age of this ticket and the fact that it was determined to be an issue on the vscode-cpptools repository, we are going to close this issue. If this issue is still occurruing, please create an issue here: [a new issue for the cpptools extension](https://github.com/microsoft/vscode-cpptools/issues/new/choose).
