### ISSUE TITLE
Debuggee TargetArchitecture not detected, assuming x86_64.

### ISSUE THREAD

**Issue by hmars-t** [microsoft/vscode-makefile-tools#224]
As can be seen from the title, I am trying to debug a simple C program on my MacBook Air with M1 chip using the makefile plugin. The compilation works without any problems, but when I try to debug the whole thing, the following error message appears.

> Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". process exited with status -1 (attach failed ((os/kern) invalid argument))

Is there any simple solution for this that I have not been able to find so far? Thanks a lot in advance.

**Comment by bobbrow** [comment]
Native ARM64 debugging is not enabled for Apple Silicon chips yet.  We're tracking support here: https://github.com/microsoft/vscode-cpptools/issues/7035

**Comment by gcampbell-msft** [comment]
@hmars-t Closing this ticket as support has been added! https://github.com/microsoft/vscode-cpptools/issues/7035#issuecomment-1063517587
