### ISSUE TITLE
Configuration for header files not found

### ISSUE THREAD

**Issue by Florin-Popescu** [microsoft/vscode-makefile-tools#225]
Hi, first of all thank you for your work with this extension. Been looking for some time to make VSCode aware of stuff in my makefiles.

My issue right now: The output window pops up for me whenever I open a .h file with the message below, even shows up again on the same file if I close it and open it again.
```
Configuration for file <filename>.h was not found. CppTools will set a default configuration.
```
I understand from [this comment](https://github.com/microsoft/vscode-makefile-tools/issues/173#issuecomment-841526341) that .h files are not compiled directly (duh!) and therefore the extension treats them differently to my .c files, but I don't understand why this message shows up, and potentially how to fix it.

#115 would fix this for me, but I feel like it's a workaround and perhaps I'm doing something wrong.
#64 looks to somewhat go in this direction, perhaps the .d files that gcc generates could be used to make the extension aware of header files?

Thanks

**Comment by andreeis** [comment]
@Florin-Popescu, thank you for creating this GitHub issue. We are wrapping up the 0.3 release which will not have the output window show up when a c/c++ language source file is opened and for which Makefile Tools did not find an IntelliSense configuration. The message will still be logged in the output channel though. This is work item https://github.com/microsoft/vscode-makefile-tools/issues/115 (but without adding a new setting).

We will not be able to get to https://github.com/microsoft/vscode-makefile-tools/issues/64 for the 0.3 release and we hope that at least not having the output window show up every time you open such file will be acceptable.

Also, we are looking into https://github.com/microsoft/vscode-makefile-tools/issues/226, to replace the message in the output channel with an item in the Problems tab. What do you think about this?

**Comment by Florin-Popescu** [comment]
Thank you, #115 is good enough for my scenario.
