### ISSUE TITLE
"terminal.integrated.automationShell" is not used when running Configure

### ISSUE THREAD

**Issue by daniel-a-melo** [microsoft/vscode-makefile-tools#233]
I have a `Makefile` that can only execute in UNIX-like shells (Linux, MSYS2, Cygwin, MacOS). It uses the find function.

```Makefile
TEST_SRC=$(shell find tests -name "*_test.c")
```

When I run configure in Windows using MSYS2, the extension seems to be executing it in a shell where find does not work as expected (is it executing on CMD, PowerShell?)

dryrun.log
```
C:\Users\user\msys64\mingw64\bin\mingw32-make.exe --dry-run --keep-going --print-directory
mingw32-make: Entering directory 'c:/Users/user/c-project'
 

File not found - *_test.c
 
File not found - *_test.c
 
File not found - *_test.c
 
mingw32-make: Leaving directory 'c:/Users/user/c-project'
```

I would expect it to respect `terminal.integrated.automationShell` setting, and run Configure in the configured shell for automation tasks, which is MSYS2's bash. 

vscode settings.json
```json
{
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Bash": {
            "env": {
                "CHERE_INVOKING": "1",
                "MSYSTEM": "MINGW64",
                "MSYS2_PATH_TYPE": "inherit",
                "PATH": "%MSYS2_HOME%\\mingw64\\bin;%PATH%"
            },
            "path": [
                "${env:MSYS2_HOME}\\usr\\bin\\bash.exe"
            ],
            "args": [
                "--login"
            ]
        },
    },
    "terminal.integrated.defaultProfile.windows": "Bash",
    "terminal.integrated.automationShell.windows": "${env:MSYS2_HOME}\\usr\\bin\\bash.exe",
    "makefile.makePath": "C:/Users/user/msys64/mingw64/bin/mingw32-make.exe"
}
```

**Comment by jankap** [comment]
I'm facing exactly the same issue. `find.exe` seems to have precedence of unix `find` which fails my Makefiles.

Same is true when calling `make` directly from `tasks.json` btw.

**Comment by andreeis** [comment]
@daniel-a-melo, @jankap, thank you for opening this bug report. It was an oversight and we will include a fix in the next release. In the meantime, can you confirm if this private vsix solves this problem for you?

https://github.com/microsoft/vscode-makefile-tools/actions/runs/1549070572

Download the vsix and run the "Install from VSIX" command that you can find via the custom menu "..." in the "Extensions" tab.

**Comment by andreeis** [comment]
Closing this since we just released a fix with Makefile Tools 0.3.1 today.

**Comment by daniel-a-melo** [comment]
@andreeis ,

Thanks very much for your attention on this issue. Unfortunately, I didn't have the chance to test it with the VSIX you made available. I will try it with 0.3.1

Btw, vscode 1.63 has just deprecated `terminal.integrated.automationShell.*` in favor of a new property. Release notes : https://code.visualstudio.com/updates/v1_63#_automationprofile-setting

**Comment by andreeis** [comment]
@daniel-a-melo, thank you for pointing out the deprecation. We should read from both then, the non-deprecated one having priority so that we don't break the users who didn't upgrade yet their terminal setting.
Let us know if you encounter any other issues with the extension.
