### ISSUE TITLE
why do you add build button to any where?

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-makefile-tools#245]
![image](https://user-images.githubusercontent.com/1876302/144565184-5f219d85-173d-42fe-9a28-82dac8474f03.png)

![image](https://user-images.githubusercontent.com/1876302/144565233-ac9acfcc-fc4a-408e-85a1-a8fe34652114.png)

![image](https://user-images.githubusercontent.com/1876302/144565293-1c86924c-f3e7-4258-9b5c-b17e4e85de26.png)

![image](https://user-images.githubusercontent.com/1876302/144565318-aec3bb32-c205-4688-8759-a116a0fdc214.png)

版本: 1.63.0-insider (system setup)
提交: cca3e817a2608225d4ae8715308195c91f765bad
日期: 2021-12-03T05:15:56.178Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393
![image](https://user-images.githubusercontent.com/1876302/144565441-82055ce3-ef1e-4c0b-b46e-bc818b69f8d9.png)

**Comment by addisonElliott** [comment]
If I'm understanding OP correctly, he's questioning why the build button is present in all sorts of places in VS Code. I think it's a valid point.

Personally, I don't think the build button should be anywhere besides the Makefile tab.

**Comment by andreeis** [comment]
@heartacker and @addisonElliott, that was a git merge mistake on our part that happened sometime during our latest PRs and we didn't notice. Thank you for catching this. The button will be fixed in the upcoming release, 0.4.

**Comment by andreeis** [comment]
Closing this since we just released a fix with Makefile Tools 0.3.1 today.
