### ISSUE TITLE
Makefile Tolls Icon on side bar gone with 0.3.0

### ISSUE THREAD

**Issue by baumra** [microsoft/vscode-makefile-tools#246]
First of all, thank you for the great extension!

For me with the update to 0.3.0 the Makefile Tools icon on the side bar is gone. When I go back to 0.2.2 it is there again.
Is this intentional?

**Comment by andreeis** [comment]
We had complaints that projects that were not Makefile based would still cause that UI and palette commands to be visible so we made sure that these are now visible only when the extension activates.
This indeed breaks the projects that don't have a makefile in the root, but use settings like "makefile.makefilePath" and "makefile.makeDirectory".
We have work item https://github.com/microsoft/vscode-makefile-tools/issues/5 which addresses more complex activation scenarios that we plan to improve.

In the mean time, what you can do, is simply run the configure command after you open your project in VSCode. Then all will show up. If not, let us know, that would be a bug we should fix asap.

**Comment by baumra** [comment]
Thanks, that explains it. We use "makefile.makefilePath". So thank you for the explanation.
As all of out projects have their Makefile buried somewhere deep in sub-directories, a common solution would be appreciated.
Meanwhile I'll use the workaround running configure manually.

**Comment by andreeis** [comment]
We just released a fix for this problem with Makefile Tools 0.3.1 today. Let us know if you encounter any other issues.

**Comment by baumra** [comment]
Unfortunately this fixed it only partly. The icon is now shown but the build does not work.
I configured some makeArgs in the makefile.configurations like this:
```
"makefile.configurations": [
        {
            "name": "release",
            "makeArgs": ["TARGET=release -sj1", "-C ./src/mycode"]
        }
]
```

The Makefile expects $(TARGET) to contain "release" in this case. But now $(TARGET) contains "release -sj1-C ./src/mycode".
The build subsequently fails.

**Comment by andreeis** [comment]
@baumra, yes let's create a new issue for this.
My first observation is that you should define 4 makeArgs instead of 2. -sj1 should be the second, the folder after -C should be the fourth... Try that and let me know how it works.

**Comment by baumra** [comment]
Ok, a new issue is not needed then. I separated the arguments and it works now. Thank you!
