### ISSUE TITLE
Implement variables and expansion mechanism

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#25]
Implement variables and expansion mechanism to make the settings more configure-able.
Example: buildLog to be defined as build_${configuration}_${target}.log
or dryrunCache_${command:makefile.buildConfiguration}_${command:makefile.buildTarget}.log if we implement the commands.

**Comment by andreeis** [comment]
@EricHripko , @nchevsky, @Florin-Popescu, @schperplata, @FrostKiwi 
While we wrap up the final testing for the 0.7.0 release, if you would like you can preview the variable expansion feature if you download [this vsix](https://github.com/microsoft/vscode-makefile-tools/actions/runs/4703905680) and install it via the "Install from VSIX" command in the palette. 

Besides the highly requested ${workspaceFolder} and ${workspaceRoot} macros that work now from any setting entry-point, we support also:
- ${userHome}
- ${env:ENVIRONMENT_VARIABLE}
- ${config:any_extension_scope.any_setting_id}
- ${command:any_extension_scope.any_command_name} (this one worked already in launch and tasks json but now they work in settings.json as well). Makefile Tools has the same launch commands we implemented for a while already and you can use any other command that is available. If it returns something useful, we'll expand with the return value.
- ${configuration} (variable syntax) and ${command:makefile.getConfiguration} (command syntax, accessible in launch tasks json as well) both return what is the current active configuration (what you selected in the left UI, either one of the entries in makefile.configurations from settings.json or "Default")
- ${buildTarget} and ${command:makefile.getBuildTarget} map to what build target you selected in the UI (or via the command set build target), so it can be "all" or any other individual target from your makefile or expands to empty if you didn't select anything in the quickPick.

If by any chance you need to pass strings with the varexp syntax and you don't want us to expand it use \\ to escape it (maybe you pass ${something} via makeArgs or binaryArgs). If that happens in a path, use forward slash for path separator so that we don't confuse it with the escape character.

If we don't recognize the pattern within ${} or something happens while running the referenced command or... we expand to "unknown".
If the first expansion resolves to another ${} varexp syntax we complain in the log that we don't support yet multiple expansion passes and the result is still "unknown". We will support more complex scenarios in future.

Any feedback?

**Comment by BigTwisty** [comment]
> @EricHripko , @nchevsky, @Florin-Popescu, @schperplata, @FrostKiwi
> Any feedback?

I didn't install the vsix file you posted, but I am now on the 0.7.0 release.  In multi-root workspaces, ${workspaceFolder:[root]} is supposed to expand to the path defined for the root [name].  Version 0.7.0 always expands to the first defined workspace, no matter what [root] is specified.

**Comment by gcampbell-msft** [comment]
@BigTwisty Thanks for your feedback! Since it seems to be behaving as expected (in regards to our implementation), but there is still desired functionality missing, I'll defer to using your new item #467 to track this, and close this. Thanks!
