### ISSUE TITLE
Build log and dryrun cache

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#26]
Some things to think through, about build log, dryrun cache and what they mean together in the Makefile Tools ecosystem.

Build log
- for now it is thought as a file path provided by the user, who has the responsibility to point to a valid and useful build log produced outside the extension
- I can see the value of having a build log saved automatically by the extension, when it has no failures
- how about saving the build log also when it fails, while keeping a last known good one available

Dryrun cache
- for now, it is thought as a file generated by the extension whenever other settings don't prevent an invocation of make with --dry-run switch. When a dryrun cache is seen as available (via the path setting), make --dry-run is not invoked anymore.  A --dry-run is invoked again (saving a new cache) when the watchers detect relevant changes have been made in settings or in makefiles.
- I realize we might want to invoke a dry-run even if there is already a cache detected, if that dryrun failed

Both of them:
- how about including the configuration and target into the name of these files, so that the extension is able to save more versions of the files instead of overriding their content
- a build or dryrun with errors may still be useful, depending on how much it failed. I'm thinking to always save the last ones, regardless of their success, but also keep a last known good.
- currently, when both defined, buildLog has priority because I thought it's something provided by the user (and it's never generated, re-generated or copied by the extension). But I see value in merging the two settings. The extension to generate many buildLog_config_target.log and dryrunCache_config_target.log from which the user can choose into one setting. Or have buildLog and dryrunCache still separated, but buildLog being generated and re-generated by the extension (as opposed to now when it's not) to separate make and make dry-run outcomes. 

If we go the multiple build and dryrun logs route, using the $ syntax or commands () to automatically include configuration and target in the file names would be nice. 
https://github.com/microsoft/vscode-makefile-tools/issues/25

**Comment by gcampbell-msft** [comment]
This seems like a stale thought experiment, I think it's safe to assume that we've made these design decisions and are pretty well into the design seeing as we're in v0.7.0 right now. Closing.
