### ISSUE TITLE
Syntax highlighting support for Makefiles

### ISSUE THREAD

**Issue by kapad** [microsoft/vscode-makefile-tools#261]

**Comment by andreeis** [comment]
@kapad, not for now. We would like to implement MAKEFILE language service support in the far future. I am going to close your GitHub report since we are tracking this feature with https://github.com/microsoft/vscode-makefile-tools/issues/208.

**Comment by bobbrow** [comment]
I think we should split out language server features since they will not likely all be implemented at once.  Reactivating this issue to track syntax colorization for Makefiles.

**Comment by brccabral** [comment]
Hi @bobbrow ,
My post #381 is not a request for new syntax highlighting, but to bring back the default highlight from before I installed this extension. Any setting? Any cached file to delete? This extension broke original highlighting...

**Comment by bobbrow** [comment]
@brccabral, sorry, I meant to comment in your issue that we don't contribute any highlighting in this extension yet so I don't know how we could be interfering with any highlighting that you currently or previously had.  Are you saying that if you uninstall our extension you get highlighting back?

**Comment by brccabral** [comment]
If I uninstall it does not come back. Basically, I lost highlighting

**Comment by bobbrow** [comment]
Hmm... the basic highlighting provided by VS Code still works for me.  Did you update VS Code or change your Theme recently?

![image](https://user-images.githubusercontent.com/12818240/200393975-15338d19-d817-474f-94bf-adc36b279170.png)
Version: 1.73.0 (user setup)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:34:06.111Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by brccabral** [comment]
Hi @bobbrow , ok, one of my other extensions had an update recently and I didn't work with Makefiles in the mean time. Disabling the other extension brings back the highlighting. I'll wait for the original request on this issue. Thank you for your support.

**Comment by bobbrow** [comment]
Thanks for the update. Glad you were able to solve the issue.

**Comment by gcampbell-msft** [comment]
Based on a recent investigation, syntax colorization is provided by a TextMate Grammar from https://github.com/microsoft/vscode/blob/main/extensions/make/syntaxes/make.tmLanguage.json, thus, closing this.
