### ISSUE TITLE
Cygwin bash make support

### ISSUE THREAD

**Issue by Rack1600** [microsoft/vscode-makefile-tools#263]
Describe the bug

OS and Version: Windows 10 version 19042.1415
VS Code Version: 1.63.2
C/C++ Extension Version: 0.3.1
Issue description:
I am using VSCode within Cygwin.  I am building a (rather large) C project in cygwin. 
It would be nice if it could just execute make in the cygwin shell, which I have added to the available windows shells, just to make my own life easier with git etc:

```
"terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        },
        "Cyg Bash": {
            "path": "C:\\cygwin64\\bin\\bash.exe",
        }
    },
```
However if I use the "Cyg Bash" as my default shell (which is my preference), then I can't see how to configure makefile tools to correctly run make, since it also uses the default shell.  
Neither 
`    "makefile.makePath": "/usr/bin/make",`
nor
`    "makefile.makePath": "C:\\cygwin64\\bin\\make.exe",`

The first results  in a conversion to "\user\bin\make.exe" which doesn't exist
/usr/bin/bash: \usr\bin\make.exe: command not found
The second doesn't work in the cygwin bash for obvious reasons. 

Would it be possible to add an option to support a linux-style command-line in a windows bash shell?

**Comment by andreeis** [comment]
@Rack1600, I will look into this. In the meantime, what happens if you don't define makePath at all and you ensure it will exist on the path?

Also, the "make.exe: command not found" error happens during the configure process or also during build (operation which opens the terminal)?
