### ISSUE TITLE
Activate on *

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#265]
Since PR https://github.com/microsoft/vscode-makefile-tools/pull/247, we are activating for any makefile within the workspace but soon  enough we validate whether there is a makefile in the root or whether -f or -C "make" arguments point to one. If not, we disable the UI and commands.

Based on this principle which for now is simple enough, we could even activate on *.

**Comment by gcampbell-msft** [comment]
I'm going to go ahead and close this one. VSCode suggests that if there are other things we can activate on, we should do that, so we shouldn't implement * activation: https://code.visualstudio.com/api/references/activation-events#Start-up.
