### ISSUE TITLE
Contributing dated?

### ISSUE THREAD

**Issue by Tim1808** [microsoft/vscode-makefile-tools#276]
Could it be that `CONTRIBUTING.md` is dated? Following the steps for installing dependencies and building compiling gives me trouble. When I use `yarn global add vsce` it says ```"Usage Error: The 'yarn global' commands have been removed in 2.x - consider using 'yarn dlx' or a third-party plugin instead"``` . Also the commands add many files that are not included in `.gitignore` ...

**Comment by andreeis** [comment]
Closing. Let me know if I misunderstood and there is still reason to keep this opened.
