### ISSUE TITLE
Keyborad shortcut "when" expression missing.

### ISSUE THREAD

**Issue by Hadatko** [microsoft/vscode-makefile-tools#279]
Hello, i didn't find a way how to enable/disable shortcut for makefile. I disabled Makefile tools extension for workspace but i am missing option how to know that. So i had to use cmake option instead:

```json
{
        "key": "ctrl+b",
        "command": "makefile.outline.buildCleanTarget",
        "when": "!cmake:enableFullFeatureSet"
}
```

I would like to use something like "when":"maketools:enabled"

**Comment by andreeis** [comment]
@Hadatko, we have "makefile:fullFeatureSet", let us now how that works for you.

**Comment by Hadatko** [comment]
Working nice thanks. I was expecting hint from IDE, so i thougt there is no option. Sorry for bothering.
