### ISSUE TITLE
Makefile Tools not selectable as configuration provider via command palette?

### ISSUE THREAD

**Issue by hurricanefrog** [microsoft/vscode-makefile-tools#286]
I have a workspace with multiple folders. Usually, I get a popup in the corner asking whether Makefile Tools should be set as Configuration provider on a new project. (One disadvantage is, for whatever reason I only get one such popup per session. Since the workspace consists of multiple folders, this is a bit cumbersome).

However, since updating the C/C++ extension to the latest version, Makefile Tools is not selectable via the command "C/C++: Select configuration provider" anymore. The lists only contains "(none)". (I did a git clean recently, since the VScode config is not checked in, this configuration was "lost").

Also, when I open an project "empty", i.e. without a file open, on configuring, Makefile Tools simply states a 

    Exception thrown during the configure process: Cannot read property 'ActiveClient' of undefined

in the Output when configuring. This is "fixed" by opening a C file. (It appears to me that the C/C++ extension is not really "loaded" before this point?).

Not sure if this is a Makefile Tools problem, or rather a problem of the C/C++ extension, so apologies if this issue is opened in the wrong repo.

Platform: Windows
VScode: 1.64.2
Makefile Tools Version: 0.3.1
C/C++ Extension Version: 1.8.4

**Comment by andreeis** [comment]
@Colengms, can you also have a look at this? I am also investigating from Makefile Tools side. It is possible I will transfer this to the CppTools GitHub repository.

**Comment by Colengms** [comment]
Hi @hurricanefrog .  Does this issue still occur for you with version 1.9.1 (pre-release) of the C/C++ extension?  I believe the error referring to `ActiveClient` has been fixed.  (https://github.com/microsoft/vscode-cpptools/issues/8887)

**Comment by hurricanefrog** [comment]
Yes, both errors (ActiveClient, Makefile Tools not selectable as IntelliSense provider) are gone when I switch to the Pre-Release version of the C/C++ extension. Many thanks.
