### ISSUE TITLE
The extension would only work when opening a c file

### ISSUE THREAD

**Issue by ryanpatiency** [microsoft/vscode-makefile-tools#289]
I have the same project, and found that this extension will only work when the first file I open in the project is a .c file, according to the debug log, this is due to the ActiveClient of cpptool havevn't been initiated. 

I was able to reproduce this bug by leaving only the .c file or the setting file open.
bug exist on both insider and stable build. newest version in 2022/3/3.

**Comment by bobbrow** [comment]
The bug you are referring to is https://github.com/microsoft/vscode-cpptools/issues/8887, and should already be fixed if you update your version of the C++ extension.  It was only an issue with the 1.9.0 pre-release.
