### ISSUE TITLE
Extension not available on the left sidebar for usage

### ISSUE THREAD

**Issue by tomsasson-fibernet** [microsoft/vscode-makefile-tools#293]
Hi, installed the extention on vscode 1.65.2 on Ubuntu 20.04 LTS , and it is active when clicking on: **C/C++: Change Configuration Provider...**
However when I search by Makefile:  I only have 3 options to choose from: Configure, Reset the Makefile Tools..., Clean configure
I also do not have the icon of the extension on the left side bar.
So, what am I doing wrong? How can I compile a Makefile project?

**Comment by andreeis** [comment]
@tomsasson-fibernet, is any "makefile" present in the root folder of your project? If not, point the extension to it via "makefile.makefilePath" then run the configure command manually and all UI (commands and left UI panel) should appear.
We have a bug that we fixed recently where the extension is not properly activated when a makefile is not found in the root. The fix will be shipped with the 0.4 release which is scheduled for early next week.

**Comment by andreeis** [comment]
We fixed several issues similar to this. Check with the latest release and reopen if you still see the symptom.
