### ISSUE TITLE
How to pass arguments do make

### ISSUE THREAD

**Issue by vbenso** [microsoft/vscode-makefile-tools#294]
Is there a way to pass arguments to make?
For instance, the number of jobs "make -jX", how can it be set in the extension?

**Comment by andreeis** [comment]
@vbenso, sure. Create a makefile configuration by defining this in your .vscode/settings.json:
"makefile.configurations": [
    {
        "name": "MySpecialConfig",
        "makeArgs": ["-jX"]
    }
]

And then go the Makefile Tools left side UI panel, click on the "Configuration" tree item, let that open a quick pick in the upper VSCode area from which you can select "MySpecialConfig". That will trigger a re-configure of your project (unless you specifically disabled it via "makefile.configureOnEdit" boolean setting) and starting that moment, all the operations invoking "make" (for the configure process or the real build) will send -jX to "make".
