### ISSUE TITLE
PreConfigure Script

### ISSUE THREAD

**Issue by Gr8-Dane** [microsoft/vscode-makefile-tools#295]
I've set the preconfigure settings as i understand them in the settings.json file. The purpose of the preconfig script is to set environment variables to shared objects for my project. But when I run the Launch Target command in the makefile display area my project can't find those dependencies during runtime. It seems like the preconfig script is being run but I'm not sure why those variables aren't being set. Here are my settings

settings.json 
 "makefile.alwaysPreConfigure": true,
    "makefile.preConfigureScript": "/absolute/path/to/set_environment.sh",
    "makefile.launchConfigurations": [
        {
            "cwd": "/path/to/bin",
            "binaryPath": "/path/to/executable",
            "binaryArgs": []
        }
    ]

Needing some help on how to troubleshoot this issue

**Comment by andreeis** [comment]
@Gr8-Dane, please set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log" in your .vscode/settings.json. Then reload your project, let it configure (unless you disable that via "makefile.configureOnOpen" it will happen automatically at project load time) and share with us your .vscode/extension.log.

**Comment by andreeis** [comment]
It appears fixed by the mentioned PR but we forgot to close this ticket. @Gr8-Dane , please confirm with the latest release if all works good.
