### ISSUE TITLE
Starting directory (cwd) "home:\username\postgres\src\bin\psql" does not exist.

### ISSUE THREAD

**Issue by JulioQc** [microsoft/vscode-makefile-tools#298]
I'm trying to compile postgresql client psql from source on Windows using msys2 for configure and makefile extension in vscode to build using the psql makefile. Configure and build are successful but whenever I get to pick launch target, it's this weird format that the terminal will not understand:

```
{
    "makefile.extensionOutputFolder": "./.vscode",
    "makefile.launchConfigurations": [
        {
            "cwd": "home:\\username\\postgres\\src\\bin\\psql",
            "binaryPath": "home:\\username\\postgres\\src\\bin\\psql\\home:\\jlacasse\\postgres\\src\\bin\\psql\\psql.exe",
            "binaryArgs": []
        }
    ]
}
```

What is that `home:` key? I believe it should equate `G:\\msys64\\home` but it's not recognized in the terminal: 

> The terminal process failed to launch: Starting directory (cwd) "home:\username\postgres\src\bin\psql" does not exist.

**Comment by andreeis** [comment]
@JulioQc, I see you closed this. We would like to assist with the problem. If this still happens for you, please set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log" in your .vscode/settings.json, reopen the project in VSCode, let Makefile Tools finish configuring and then share with us the files "dryrun.log" and "extension.log" from your ".vscode" subfolder.

**Comment by JulioQc** [comment]
Use git bash (w/ windows flex bison) instead of msys2 to run configure so full path is used instead of path relative to msys2 shell sandbox.

Makefile will then generate proper launch config.
