### ISSUE TITLE
Version 4.0 working at all?

### ISSUE THREAD

**Issue by GabrielWelvaert** [microsoft/vscode-makefile-tools#302]
![image](https://user-images.githubusercontent.com/61606105/161166530-4b14c3ac-a7bf-4035-b141-4cc77c59cd7c.png)

I have a valid Makefile in the root of my folder where I am running my main c++ file but I cant run the make command, makefile, nmake, etc out of the terminal. Is anyone else having this issue?

**Comment by bobbrow** [comment]
Did you solve your issue?  We haven't seen that error, but we'd like to understand if we broke something in the last release.

**Comment by GabrielWelvaert** [comment]
> 

Hi Bob, thanks for reaching out. I still don't fully understand what was going on, but I was able to fix the issue after a few hours of tweaking things on my end. Version 4.0 is now working fully for me. Thank you!

**Comment by andreeis** [comment]
@GabrielWelvaert, was the tweaking simply VSCode infrastructure related (install/uninstall extensions, updates, etc...) or Makefile Tools specific ("makefile.*" settings in .vscode/settings.json)?
