### ISSUE TITLE
#region folding should be supported

### ISSUE THREAD

**Issue by KevinMGranger** [microsoft/vscode-makefile-tools#303]
This would be useful to divide a makefile by section.

**Comment by andreeis** [comment]
@KevinMGranger, thank you for the suggestion. We use the work item https://github.com/microsoft/vscode-makefile-tools/issues/208 to track various language services features, like this one you propose. Closing this as a duplicate.

**Comment by HoLengZai** [comment]
If this extension can be built-in in vscode it could be great
[#region folding for VS Code](https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder)
