### ISSUE TITLE
vscode_nls_1.localize is not a function

### ISSUE THREAD

**Issue by kemadev** [microsoft/vscode-makefile-tools#305]
Issue Type: <b>Bug</b>

Set up Makefile extension, with build and launch target, then try to run or debug the selected program (from Ctrl Shit P or with mouse on extension pannel)

Error appears in notification area or as a popup (if you run from pane / Ctrl Shift P) : vscode_nls_1.localize is not a function

Everything works as expected (runs / launch a debug session) if we omit the error message
Seems like just one exception is raised but can be omitted

Extension version: 0.4.0
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:41.156Z)
OS version: Linux x64 5.16.0-kali6-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.47GB (1.83GB free)|
|Process Argv|--unity-launch --crash-reporter-id 953b0c26-c497-4f79-90b4-92236704976f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by andreeis** [comment]
@kemadev, is this working now? I saw your comment that it got fixed after a reboot. But then you reopened again. Let us know if this still happens for you and also how much the reboot helped, when it started to fail again, maybe we'll find clues there. We didn't see this error. Maybe we can figure out something that is special on your system that would help us reproduce on our side to investigate.

**Comment by kemadev** [comment]
@andreeis Unfortunately no, I still experience the issue, even on an iMac running macOS 10.14.6 (18G103)
Everything else works just fine, there is just the warning notification

**Comment by andreeis** [comment]
@kemadev, I was able to reproduce the problem and we will release a patch for the extension.

**Comment by p1x44r** [comment]
Exact same issue here. When I do get it to run it's the message I get. Most of the time it doesn't do anything at all.

macOS 12.3.1
MBP 2019

**Comment by andreeis** [comment]
@p1x44r, we will release a patch update of Makefile Tools soon, most probably sometime this week.
Until then, if you want, you can download the vsix from [here](https://github.com/microsoft/vscode-makefile-tools/actions/runs/2222777962) and install it via "Install from VSIX" context menu in the "Extensions" left UI panel in VSCode. If the problem is not fixed for you let us know.

**Comment by p1x44r** [comment]
Thank you @andreeis !

**Comment by andreeis** [comment]
@p1x44r, @kemadev this fix is in Makefile Tools 0.5.0 which was released today. Upgrade this extension in VSCode and let us know if you encounter any other issues.

**Comment by kemadev** [comment]
Seems to be fixed to me, thanks !
