### ISSUE TITLE
Multiroot workspace and makefile tools: Makefile entry point not found

### ISSUE THREAD

**Issue by IstiCusi** [microsoft/vscode-makefile-tools#311]
I have troubles to get the make file tools running with a multi root workspace. Whatever I do, I get a
`Makefile entry point not found` error pop. Is it possible to uset the makefile tools with multi root 
workspaces. How can I point the makefile tools to the given makefile of the project folders. 
Thank you very much for your help and clarification. In case it is not possible with multi root, I suggest
to add this as commend to the documentation.

Update: I tested it in a standard non-multiroot project -- there the plugin works fine.

VS:
Version: 1.61.1
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:15:35.620Z (6 mos ago)

Thank you very much and cheers,
Stephan

**Comment by andreeis** [comment]
@IstiCusi, we are tracking the implementation for multiroot workspace with work item https://github.com/microsoft/vscode-makefile-tools/issues/90.
Read in there some possible work arounds that may help you even before we implement this support. Not perfect but maybe good enough for now. If you encounter any problems on that route let us know.
Closing as a duplicate for now.
