### ISSUE TITLE
How to open GCC source folder?

### ISSUE THREAD

**Issue by HyperForce** [microsoft/vscode-makefile-tools#320]
https://gcc.gnu.org/install/configure.html
"First, we highly recommend that GCC be built into a separate directory from the sources which does not reside within the source tree. "

**Comment by andreeis** [comment]
@HyperForce, I see that you closed this issue. I hope that you are unblocked and do not have any problems using the Makefile Tools extension on the GCC repository.
Regarding where the binaries are built, the Makefile Tools extension is not deciding the location, it just triggers the "make" command according to the settings the user sets. Let us know in detail if you found that the extension is not doing something as you would expect.
