### ISSUE TITLE
-C flag not working as expected

### ISSUE THREAD

**Issue by yoko911** [microsoft/vscode-makefile-tools#323]
Configuration as follows:

{
            "name" : "external make",
            "makeArgs" : [
                "-C /Users/dariovazquez/work/externalmake"]
        }

Getting an error

make: ***  /Users/dariovazquez/work/externalmake: No such file or directory.  Stop.
The terminal process "/bin/zsh '-c', ''make' '-C /Users/dariovazquez/work/externalmake'

Need to be able to run a makefile that is on another file that contains some scripts to generate an image file

**Comment by bobbrow** [comment]
Can you try this?
```
{
"name" : "external make",
"makeArgs" : [
  "-C",
  "/Users/dariovazquez/work/externalmake"]
}
```
Each string is expected to be its own arg.  If we detect spaces in the args we will quote them.

**Comment by yoko911** [comment]
that worked, thanks!

**Comment by bobbrow** [comment]
Glad that worked for you. 👍  Let us know if you need anything else.  If you are happy with the extension and would be willing to [post a review](https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools&ssr=false#review-details), it helps us continue to develop this extension.  Thanks!

**Comment by arurke** [comment]
Can I suggest to update the CircuitPython example in https://github.com/microsoft/vscode-makefile-tools/blob/main/docs/repositories.md with this fix?

**Comment by arurke** [comment]
@gcampbell-msft Sorry for the late reply, I suggest updating repositories.md to reflect the split syntax, e.g. from
```
 "makeArgs": [
                "-C mpy-cross"
             ]
```
to
```
 "makeArgs": [
                "-C",
                "mpy-cross"
             ]
```

**Comment by gcampbell-msft** [comment]
@arurke Thanks! Updated.

**Comment by arurke** [comment]
https://github.com/microsoft/vscode-makefile-tools/pull/714
