### ISSUE TITLE
Stores logs in ${repo}/.vscode/

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/vscode-makefile-tools#329]
The extension is, for some reason, writing log files into my repos instead of somewhere in my home directory, or a temp dir.

Every time I open a workspace, this extension is writing `configurationCache.log` and `dryrun.log` into the `.vscode/` folder of the first repo in the (multi-root) workspace.

My source repo is not your temp or logs dir :)

**Comment by bobbrow** [comment]
Thanks for the feedback.  Many of the people we talk to ignore the .vscode folder, but we understand that not everyone does.  You can change the behavior with the `makefile.extensionOutputFolder` setting.

**Comment by mgabeler-lee-6rs** [comment]
No other vscode extension I've used defaults to putting logs in the source dir. There are even multiple directories just for logs in my ~/.config/Code/ directory

I would suggest this extension ought to change its defaults to be consistent with other members of the ecosystem

**Comment by mgabeler-lee-6rs** [comment]
> You can change the behavior with the `makefile.extensionOutputFolder` setting

This setting is broken in many and strange ways. Filed #331 for that issue since it's really separate from this

**Comment by tbehling** [comment]
> Many of the people we talk to ignore the .vscode folder, but we understand that not everyone does.

Hi @bobbrow, this statement is confusing to me because this very repo contains a .vscode folder with three files in it.

I have observed two incidents where a developer's credentials (otherwise held only in memory, as env vars) were accidentally pushed to a Git repo because of the logging behavior of this VS Code extension.

Would it be possible to update this project so that environment variables are not dumped into a log file on disk?

**Comment by andreeis** [comment]
@tbehling, can you detail in what log the environment variables were written and during what operation? I set the logging to most verbose level, I went through a complete configure, built target...etc and I did not see my new temporary environment variable that I set for this purpose. What were the files that got accidentally checked in?
The only situation where we write the environment variables is at the end of pre-configure and we write them into the user temporary folder. Is that (%TEMP%\wrapPreconfigureScript.out) the file that got accidentally checked in? If that's what it is, we can make sure we delete it once we're done with processing it's content.

**Comment by bobbrow** [comment]
@tbehling fair enough. 

@andreeis let's just change the default value for `makefile.extensionOutputFolder` to empty string and when it is empty/unset we use `vscode.ExtensionContext.storageUri` or `vscode.ExtensionContext.logUri`.  VS Code will give us a path to use that is outside the workspace and shouldn't mess with source control.  We have to create the folder at that path, but that is fine.  The path is not very discoverable and may leave files on the machine that the user is unaware of, but that seems better than writing stuff in the workspace that users might accidentally check in to source control.

**Comment by andreeis** [comment]
@tbehling, @mgabeler-lee-6rs, a fix for this problem was released today with Makefile Tools 0.6.0. Let us know if you encounter any other issues.

**Comment by tbehling** [comment]
This is great, thank you so much for the attention to this!
