### ISSUE TITLE
feat

### ISSUE THREAD

**Issue by PeterZhongCFS** [microsoft/vscode-makefile-tools#330]
It seems that this tool cannot help if I use 'makefile' as the make file.

**Comment by andreeis** [comment]
@PeterZhongCFS, can you detail more about the problem you are seeing? The extension should activate and offer its features when it finds a "makefile" or "Makefile" in the root folder, or anywhere down below (but in that case you also need to set "makefile.makefilePath".

Is your makefile in the root of the folder you open in VSCode or is it somewhere else?

**Comment by andreeis** [comment]
Closing as too old "more info needed". Please reactivate if this still happens and please provide information for us to investigate.
