### ISSUE TITLE
Changing makefile.extensionOutputFolder at user level is undone by extension

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/vscode-makefile-tools#331]
Attempting to apply the workaround from https://github.com/microsoft/vscode-makefile-tools/issues/329#issuecomment-1136238037, I found the recommended solution does not work properly.

Repro process:

1. Load a multi-root workspace
2. Open vscode settings
3. Change `makefile.extensionOutputFolder` at the User level

Expected outcome: The setting is changed and takes effect

Actual outcome: The extension _immediately_ adds an override to my workspace file to set it back to the default `./.vscode`

Gets worse:

1. Close vscode
2. Open workspace file in a text editor and remove that override, save
3. Open vscode again

Result: Extension immediately re-adds that same override.

Gets even worser:

1. Give up and add the override to the workspace file too
2. Close & reopen vscode

Expected result: Extension obeys the specifically saved setting

Actual result: Extension _still_ deletes my custom setting and overwrites it with the default setting

**Comment by andreeis** [comment]
@mgabeler-lee-6rs, I was surprised about this behavior and when I inspected the code I saw that the extension intentionally falls back to the default, in case the given output folder doesn't exist. This looks by design but indeed, instead of doing this we can simply create the folder we read that the user has set in case it's not there.

Unless there is an extra bug about persisting this setting, do you confirm that this setting works fine for you if the folder you want to use as "makefile.extensionOutputFolder" exists on your drive?
If not we'll investigate extra, additionally to the other two work items that we intend to address: "default value change" and the "create folder instead of falling back to default value" behavior.

**Comment by mgabeler-lee-6rs** [comment]
Thanks for the pointer. The workaround there doesn't work for me, but I'll watch the issue for updates :)

**Comment by jmaargh** [comment]
This caused me to immediately removed the extension. All I wanted was syntax highlighting and I ended up with an extension that was auto-editing files in my git history (specifically, `.vscode/settings.json`.

When I deleted the offending line it just immediately re-added itself on save.

**Comment by andreeis** [comment]
@jmaargh, do you remember which was the setting that was automatically and stubbornly saved by the extension? Of course, we are not saving anything without the user approval or explicit interaction. I just double checked some core scenarios and I am not able to make any setting just show up in my .vscode/settings.json. Help me find the trigger for this bug so we fix it asap.

**Comment by jmaargh** [comment]
IIRC it was `extensionOutputFolder`. Similar (if not exactly the same) workflow to that described above. I was trying to get this extension to stop spamming my repo with log files, then it started misbehaving with my workspace `settings.json` when I tried to change the setting.

**Comment by bobbrow** [comment]
I believe the problem starts here:
https://github.com/microsoft/vscode-makefile-tools/blob/8293f8d56fed2637d30c0c68fb81701e893b7852/src/configuration.ts#L331

We should try to create the folder if it doesn't exist.

**Comment by bobbrow** [comment]
I think we should do [#329](https://github.com/microsoft/vscode-makefile-tools/issues/329#issuecomment-1205804550) as well.

**Comment by jmaargh** [comment]
It's my strong opinion that the following line should not be used at all: https://github.com/microsoft/vscode-makefile-tools/blob/8293f8d56fed2637d30c0c68fb81701e893b7852/src/configuration.ts#L336

Even if my settings file has complete nonsense in that field, I don't want an extension editing it for me I'd rather you just log the error and not try to write anything to the missing/nonsense directory.

**Comment by icedream** [comment]
I was surprised to see this extension messing with the workspace VSCode settings as well when I installed this extension. I was unable to find out how to get rid of the behavior before finding this issue so I had no choice but to completely disable or uninstall the extension.

For me it would be fine for the extension to notify me that something is wrong with my settings or that I still need to configure it properly after installation.

**Comment by bobbrow** [comment]
It shouldn't be necessary to update the settings.  We can override the value in case of failure without updating the settings.  The code should be removed.  We'll get it done this week.

**Comment by jmaargh** [comment]
Great, thanks for addressing this @bobbrow

**Comment by andreeis** [comment]
@jmaargh, @icedream, @mgabeler-lee-6rs, a fix for this problem was released today with Makefile Tools 0.6.0. Let us know if you encounter any other issues.
