### ISSUE TITLE
Is there a reason why this still has not been fixed yet

### ISSUE THREAD

**Issue by ispeedyg** [microsoft/vscode-makefile-tools#335]
and yet you still have it up in the extension downloads for VS. I have now spent 2 days trying to get a makefile work with your extension and now just pissed. take this extension off it is worthless if you cannot guide it to the specific directory which is inside of the root folder that has a path set to the folder in the environments.
<img width="676" alt="makefileNoMakefile" src="https://user-images.githubusercontent.com/12056754/175948644-d55c0f0d-362c-457c-8759-0858af53f642.png">
Since you think wasting other peoples time but putting up a broken extension that has been going on for years gives you any kind of quality reputation. If i were Julia Reid I would have that video taken down where she promotes this POS.

**Comment by bobbrow** [comment]
@andreeis can you check if we are inserting that `,` in the path?  I'm taking a look now, but not finished yet...

@ispeedyg I'm sorry that you're frustrated. This extension works for lots of people and we'd be happy to help you get it working as well.  The screenshot you shared is showing your "User" settings, but these can be overridden by the "Workspace" and "Folder" settings.  Could you double check the settings for those tabs and see if a comma was accidentally inserted somewhere?

**Comment by andreeis** [comment]
@bobbrow, from my memories since I implemented this and also by reading the code I didn't find any situation that would explain that comma in the screenshot.

@ispeedyg, do you have a small repro available or maybe your project is open source and I can just clone it?

If not, can you set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log" in your .vscode/settings.json, reload the project in VSCode from the root, let it finish configure (you should see a "configure finished" in the Makefile Tools Output Channel) then share for us two files: .vscode/dryrun.log and .vscode/extension.log?

**Comment by bobbrow** [comment]
I think it's this repo: https://github.com/luarocks/luarocks
But if that's right, I don't see much C or C++ in there.  I also see a GNUMakefile which we don't support yet either. (#95)

**Comment by ispeedyg** [comment]
all i needed was for the plugin to put in what it needed to make the damn execute. it didn't and for the other person. I copied it directly from either command or explorer. I have gone back a few months on my images of my computer since i did a lot of installing and uninstalling of this and that and the other thing. So will be a little bit before i get back to the install of LuaRocks.

**Comment by ispeedyg** [comment]
I’m going back in time now decided to bring back an install from a few months ago. I have installed and uninstalled to many programs I don’t know what I’ve done anymore. Going to sleep for a few hour while this re this reinstall. I did try another makefile I guess node.is has a new update. I couldn’t get the makefile to find it either. My install of node was screwing up anyway to

Sent from my iPhone

On Jun 27, 2022, at 1:01 PM, Bob Brown ***@***.***> wrote:

﻿

I think it's this repo: https://github.com/luarocks/luarocks
But if that's right, I don't see much C or C++ in there. I also see a GNUMakefile which we don't support yet either. (#95<https://github.com/microsoft/vscode-makefile-tools/issues/95>)

**Comment by bobbrow** [comment]
Ok. Let us know if we can help with anything.  If you are using that LuaRocks repo though, I don't think our extension will currently be of help to you since it's not a C++ repo and we don't support GNUMakefiles yet.
