### ISSUE TITLE
How to `#include` some headers in .gitignore

### ISSUE THREAD

**Issue by gtianw** [microsoft/vscode-makefile-tools#340]
Bug type: Language Service

**Describe the bug**
- OS and Version:Windows 10 Pro
- VS Code Version:1.68.1
- C/C++ Extension Version:1.10.7
- Other extensions you installed (and if the issue persists after disabling them):None
- If using SSH remote, specify OS of remote machine:No

When I open the FFmpeg project, header files in &ldquo;.gitignore&rdquo; cannot be included. The problem may be associated with subdirectories.
Such as &ldquo;config.h&rdquo; and &ldquo;libavutil/avconfig.h&rdquo;, which are generated by `configure`. But these files, have important global symbols, must be included for parsing completely.

**Screenshots**

&ldquo;config.h&rdquo; is ignored by &ldquo;.gitignore&rdquo; in `ffmpeg_root`.
- `#include "config.h"` in &ldquo;fftools/ffplay.c&rdquo;, without &ldquo;.gitignore&rdquo; in `fftools/`:
![image](https://user-images.githubusercontent.com/91190888/176867571-4c08e400-96c8-42c3-88bb-557bc053a0fd.png)
- `#include "config.h"` in &ldquo;libavutil/adler32.c&rdquo;, with a &ldquo;.gitignore&rdquo; in `libavutil/`:
![image](https://user-images.githubusercontent.com/91190888/176868208-44a0f2e8-6c4e-4c5e-9e22-9451b8ce212a.png)

**Comment by andreeis** [comment]
@gtianw , does this still happen? If no please confirm so we can close.
If yes, please set
"makefile.loggingLevel": "Debug",
"makefile.extensionOutputFolder": "./MyOutputFolder",
"makefile.extensionLog": "extension.log"

Reopen your project in VSCode, let it finish configure and then share with us files from ./MyOutputFolder: dryrun.log and extension.log.

**Comment by gtianw** [comment]
The problem is not caused by the extension.
The reason is that my VSCode haven't launch from msys2.
