### ISSUE TITLE
The value of miDebuggerPath is invalid in Ubuntu

### ISSUE THREAD

**Issue by karriszou** [microsoft/vscode-makefile-tools#341]
**Operating System:** _Ubuntu 20.04 LTS_
**output of type 'code -v'**:
_1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64_

There is a strange issue: everytime i restart Ubuntu and press the **Debug button of the makefile-tool** to debug the program, an error message appears: **Unable to start debugging. The value of miDebuggerPath is invalid**

This is my settings.json:
**{
    "makefile.extensionOutputFolder": "./.vscode",
    "makefile.makePath": "/usr/bin/make",
    "makefile.configurations": [
        {
            "name": "mydebug",
            "makeArgs": []
        }
    ],
    "makefile.launchConfigurations": [
        {
            "miDebuggerPath": "/usr/bin/gdb",
            "MIMode": "gdb",
            "stopAtEntry": false,
            "cwd": "/home/code/ioq3/build/debug-linux-x86_64",
            "binaryPath": "/home/code/ioq3/build/debug-linux-x86_64/ioquake3.x86_64",
            "binaryArgs": [
                "+map", "q3dm3", "+set", "developer", "1", "+set", "sv_pure", "0", "+set", "vm_game", "0", "+set", "vm_cgame", "0", "+set", "vm_ui", "0"
            ]
        }
    ],
    "C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools",
}**

the makefile-tool 'Configuration' option is "mydebug" not "Default".
**the outpt of type 'which gdb'**: _/usr/bin/gdb_, the same as "miDebuggerPath" option.

The first two times I set the miDebuggerPath option to "", **and there is no lauch.json and tasks.josn file**, somehow I can debug the program from makefile-tool (not F5). But when I restart Ubuntu for the third time and debug program the error always appears no matter if I set miDebuggerPath to "/usr/bin/gdb" or "", i don't know if this is a bug or a configure error.

How can I debug my program from makefile-tool (not F5), can someone help me?

**Comment by karriszou** [comment]
This time i set the 'miDebuggerPath' to "/usr/bin", and it debug program successful. I don't know why...

**Comment by karriszou** [comment]
> @karriszou, I looked at the implementation of the logic we use when setting MIMode and miDebuggerPath (it depends on what compiler is used, what operating system and of course what settings the user defines) and I see how we assume that miDebuggerPath is just a folder, not a full path. We append MIMode to miDebuggerPath. Of course we can do a check to prevent a second append and I'm leaving this work item open to address later. In the meantime, if you set miDebuggerPath only to "/user/bin", does it work consistently?

Thanks for your replay! 

> if you set miDebuggerPath only to "/user/bin", does it work consistently?

Yes, I restarted my Ubuntu many times these days and it worked correctly every time, at least on my computer.

It looks like it (miDebuggerPath) is indeed being treated as a folder.

**Comment by andreeis** [comment]
@karriszou , a fix for this will be released with 0.7 next week but if you would like to see how this works earlier you can install one vsix from [this link](https://github.com/microsoft/vscode-makefile-tools/actions/runs/4451312188).

go to the Extensions panel on the left
click "..."
run "Install from vsix" from the context menu

Let us know if you encounter any other issues or if you have any other suggestions/recommendations in this area of functionality.

**Comment by gcampbell-msft** [comment]
Completed in 0.7.0. Closing! 👍
