### ISSUE TITLE
problem in using esp-idf

### ISSUE THREAD

**Issue by Aishwarya4598** [microsoft/vscode-makefile-tools#342]
Issue Type: <b>Performance Issue</b>

please help

Extension version: 0.5.0
VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:24.514Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (1.53GB free)|
|Process Argv|--crash-reporter-id ad4b147f-b756-4746-9a1e-97f6d2b306e2|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   126	 19216	code main
    0	   232	  2876	   window (Extension: Espressif IDF - main - Visual Studio Code)
    0	   106	  4696	   shared-process
    0	    77	 15640	     fileWatcher
    0	    63	 18668	     ptyHost
    0	    45	 12104	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 15632	       console-window-host (Windows internal process)
    0	    23	 15432	   crashpad-handler
    1	    94	 15932	   issue-reporter
    0	    38	 16748	   utility-network-service
    0	   160	 17872	   extensionHost
    0	    74	 15588	     "C:\Users\aishw\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\aishw\.vscode\extensions\espressif.esp-idf-extension-1.4.0\dist\kconfigServer.js --node-ipc --clientProcessId=17872
    0	    76	 17544	     "C:\Users\aishw\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\aishw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=17872
    0	    11	 19224	     c:\Users\aishw\.vscode\extensions\ms-vscode.cpptools-1.10.8-win32-x64\bin\cpptools.exe
    0	     6	 14668	       console-window-host (Windows internal process)
    0	     4	 15292	       "c:\Users\aishw\.vscode\extensions\ms-vscode.cpptools-1.10.8-win32-x64\bin\cpptools.exe"
    0	   167	 18352	   gpu-process
    0	    97	 18692	   window (undefined)
    0	    91	 18884	   window (undefined)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: Espressif IDF - main - Visual Studio Code)
|    Folder (main): 4 files
|      File types: c(1) txt(1) mk(1) projbuild(1)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550

```

</details>

**Comment by andreeis** [comment]
@Aishwarya4598, let's figure out what's causing this performance issue. If your project is open source or easy to share, send that over: a link for us to clone or you can also send email to makefiletools@microsoft.com if you have more sensitive components in your project.

As a start, you can also set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log" in your ".vscode/settings.json", then reload the project, let it finish configuring (or if it never finishes, let it get into the problem), then share with us the files "dryrun.log" and "extension.log" from your ".vscode" subfolder.

**Comment by andreeis** [comment]
@Aishwarya4598 , closing this "more info needed" as old but please reactivate if this still happens and provide the info requested which will help us reproduce on our side and investigate.
