### ISSUE TITLE
Does not run build target if you point a Makefile inside a 'make' named directory with relative path

### ISSUE THREAD

**Issue by daninsky1** [microsoft/vscode-makefile-tools#350]
If you point a Makefile inside a directory called 'make' relative, like this:
`"makefile.makefilePath": "./make/.../Makefile" `the extension generate a erroneous make command `make/make`:
`fish: Unknown command: make/make`

The workaround is to use an absolute path or renaming that directory in which is a direct child of current working directory that contains the Makefile.

**Comment by andreeis** [comment]
@daninsky1, I am not able to reproduce this. Please share any settings specific to the extension ("makefile.*") that you have in your .vscode/settings.json (and user lever if any).
Also set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log", reload, let your project finish configuring and share with us .vscode/dryrun.log and .vscode/extension.log.
I'm sure there's a bug somewhere and once we see more logging from you we'll figure out what it is and how to fix it.

**Comment by daninsky1** [comment]
Configuration:
`    "C_Cpp.default.configurationProvider": "ms-vscode-makefile-tools",
    "makefile.launchConfigurations": [
        {
            "cwd": "./build/",
            "binaryPath": "./build/inkbreakerdebug",
            "binaryArgs": []
        }
    ],
    "makefile.makefilePath": "make/Makefile",`

dryrun.log:
`make/make all -f /mnt/F/dev/inkbreaker/make/Makefile --dry-run --always-make --keep-going --print-directory
/bin/sh: 1: make/make: Permission denied

extension.log:
`Configurations cached at /mnt/F/dev/inkbreaker/.vscode/configurationCache.log
No folder path to the makefile is defined in the settings file.
Always pre-configure: false
Dry-run switches: --always-make,--keep-going,--print-directory
Additional compiler names: 
Exclude compiler names: 
No current configuration is defined in the workspace state. Assuming 'Default'.
Reading current build target "all" from the workspace state.
Reading current launch configuration ".>./build/inkbreakerdebug()" from the workspace state.
Default launch configuration: MIMode = undefined,
                    miDebuggerPath = undefined,
                    stopAtEntry = undefined,
                    symbolSearchPath = undefined
Configure on open: true
Configure on edit: true
Configure after command: true
Only .PHONY targets: false
Save before build or configure: true
Build before launch: true
Clear output before build: true
Ignore directory commands: true
compile_commands.json path: null
Deduced command 'make/make -f /mnt/F/dev/inkbreaker/make/Makefile' for configuration "Default"
Saving opened files before build.
Configuring from cache: /mnt/F/dev/inkbreaker/.vscode/configurationCache.log
Load configuration from cache elapsed time: 0.042
Sending Workspace Browse Configuration: -----------------------------------
    Browse Path: 
    Standard: undefined
    Compiler Path: undefined
    Compiler Arguments: 
----------------------------------------------------------------------------
Generating in the background a new configuration cache with command: 'make/make all -f /mnt/F/dev/inkbreaker/make/Makefile --dry-run --always-make --keep-going --print-directory'
Writing the dry-run output: /mnt/F/dev/inkbreaker/.vscode/dryrun.log
Spawning child process with:
 process name: make/make
 process args: all,-f,/mnt/F/dev/inkbreaker/make/Makefile,--dry-run,--always-make,--keep-going,--print-directory
 working directory: /mnt/F/dev/inkbreaker
 shell type: default
Generating dry-run elapsed time: 0.069
The make dry-run command failed.
IntelliSense may work only partially or not at all.
/bin/sh: 1: make/make: Permission denied


You can see the detailed dry-run output at /mnt/F/dev/inkbreaker/.vscode/dryrun.log
Make sure that the extension is invoking the same make command as in your development prompt environment.
You may need to define or tweak a custom makefile configuration in settings via 'makefile.configurations' like described here: [link]
Also make sure your code base does not have any known issues with the dry-run switches used by this extension (makefile.dryrunSwitches).
If you are not able to fix the dry-run, open a GitHub issue in Makefile Tools repo: https://github.com/microsoft/vscode-makefile-tools/issues
Preprocessing: "/mnt/F/dev/inkbreaker/.vscode/dryrun.log"
Preprocess elapsed time: 0
Parsing for IntelliSense.
Updating the CppTools IntelliSense Configuration Provider.
Parsing dry-run output for CppTools Custom Configuration Provider.
Sending Workspace Browse Configuration: -----------------------------------
    Browse Path: 
    Standard: undefined
    Compiler Path: undefined
    Compiler Arguments: 
----------------------------------------------------------------------------
Parsing for IntelliSense elapsed time: 0.006
Parsing for launch targets.
No launch configurations have been detected.
Complete list of launch targets: 
Parsing for launch targets elapsed time: 0.01
Generating parse content for build targets.
Generating targets information with command: 'make/make all -f /mnt/F/dev/inkbreaker/make/Makefile --print-data-base --no-builtin-variables --no-builtin-rules --question'
Writing the dry-run output: /mnt/F/dev/inkbreaker/.vscode/targets.log
Spawning child process with:
 process name: make/make
 process args: all,-f,/mnt/F/dev/inkbreaker/make/Makefile,--print-data-base,--no-builtin-variables,--no-builtin-rules,--question
 working directory: /mnt/F/dev/inkbreaker
 shell type: default
Generating dry-run elapsed time: 0.041
Parsing for build targets from: "/mnt/F/dev/inkbreaker/.vscode/targets.log"
No build targets have been detected.
Complete list of build targets: 
Parsing build targets elapsed time: 0.001
Configure finished. The status for all the subphases that ran:
loadFromCache: return code = 0, elapsed time = 0.042
generateParseContent: return code = 126, elapsed time = 0.069
preprocessParseContent: return code = 0, elapsed time = 0
parseIntelliSense: return code = 0, elapsed time = 0.006
parseLaunch: return code = 0, elapsed time = 0.01
dryrunTargets: return code = 126, elapsed time = 0.041
parseTargets: return code = 0, elapsed time = 0.001
Configure succeeded.
Sending telemetry: eventName = configure
properties: firstTime = "false",makeDryRun = "true",readCache = "true",isClean = "true",processTargetsSeparately = "false",resetBuildTarget = "false",triggeredBy = "configure dirty (on open), settings (configureOnOpen)",buildTarget = "all"
measures: numberBuildTargets = "0",numberLaunchTargets = "0",numberIndexedSourceFiles = "0",numberMakefileConfigurations = "0",totalElapsedTime = "0.222",exitCode = "0",loadFromCache.exitCode = "0",loadFromCache.elapsed = "0.042",generateParseContent.exitCode = "126",generateParseContent.elapsed = "0.069",preprocessParseContent.exitCode = "0",preprocessParseContent.elapsed = "0",parseIntelliSense.exitCode = "0",parseIntelliSense.elapsed = "0.006",parseLaunch.exitCode = "0",parseLaunch.elapsed = "0.01",dryrunTargets.exitCode = "126",dryrunTargets.elapsed = "0.041",parseTargets.exitCode = "0",parseTargets.elapsed = "0.001"
Configure elapsed time: 0.222
Sending telemetry: eventName = settings
properties: makefile.launchConfigurations.cwd = "...",makefile.launchConfigurations.binaryPath = "...",makefile.loggingLevel = "Debug",makefile.makeDirectory = "undefined",makefile.makefilePath = "...",makefile.extensionLog = "..."
Building current target before launch: "all"
Saving opened files before build.
Building target "all" with command: 'make/make all -f /mnt/F/dev/inkbreaker/make/Makefile'
Executing task: "Makefile Tools Build Task" with quoting style "Strong"
 command name: make/make
 command args all,-f,/mnt/F/dev/inkbreaker/make/Makefile
Target "all" failed to build.
Sending telemetry: eventName = build
properties: exitCode = "126",target = "all",triggeredBy = "command pallette (buildTarget)"
measures: buildTotalElapsedTime = "0.727"
Building target "all" failed.
`
`

**Comment by andreeis** [comment]
@daninsky1, I am still not reproducing this. I tried windows, mingw and wsl (which is your scenario, judging from the logs I see, right?). Let's find more details of your situation which can trigger this.
Where is the "make" executable, in what path? Do you use "makefile.makePath" or not? Do you have also a "make" executable in the "make" subfolder by any chance? Or it's only the makefile in there?

**Comment by daninsky1** [comment]
Not really, i'm using directly on linux, and I don't have any make executable in the subfolders, an interest thing maybe is, my Makefile call another make command to compile the program dependency.

**Comment by daninsky1** [comment]
That's the make file I'm using
[https://github.com/daninsky1/inkbreaker/blob/main/make/Makefile](url)

**Comment by gcampbell-msft** [comment]
Hi, @daninsky1 , is this issue still giving you trouble? 

I'm investigating this, and similar to what Andreea was trying to do, I'm attempting to repro your issue. 

I have one question to start with as I start to investigate: 

1. What version of the extension are you using? 
2. Could you send us any settings relative to the makefile path? `makefile.makePath`, `makefile.makefilePath`, `makefile.makeDirectory`. These may help us diagnose this issue, and give us some more information to try and repro it. 

Thanks!

**Comment by daninsky1** [comment]
I have no time available at the moment to do the tests, but thanks.
