### ISSUE TITLE
No Makefile Perspective

### ISSUE THREAD

**Issue by saulspatz** [microsoft/vscode-makefile-tools#359]
I just installed Makefile tools v0.6.0, and there is no new perspective, that is the C++ and gear icon does not appear.  I am running Xubuntu 20.04.5 LTS with VS Code 1.71.0.  In accordance with advice given in another question I typed "Makefile: configure" in the command palette, but no GUI appeared anywhere.  I was able to enter the path to my Makefile, but I can't figure out how to configure, build, and debug my my project.  At about 8:11 of this video https://www.youtube.com/watch?v=cEC2iZCS2Lk , a UI is shown for doing this.  Is there any way I can make the UI show up?  If not, is it possible to do the same thing manually, and if so, how?

Thanks for any help you can give me.

**Comment by saulspatz** [comment]
Don't bother

**Comment by bobbrow** [comment]
Hi there,

Sorry for the silence. We've been dealing with some sickness and missed a few days looking at this repository.  If you can set the `makefile.loggingLevel` setting to `Debug` and then reload VS Code and rerun the `Makefile: configure` command, the extension will print out some logging information that might help us figure out what's going wrong if you'd be willing to share that with us.

**Comment by andreeis** [comment]
@saulspatz, also can you share how you point to the makefile? How are you writing the setting "makefile.makefilePath"?
Where is the makefile compared to the folder that you are opening in VSCode?

**Comment by saulspatz** [comment]
Doesn't matter; I've already uninstalled the extension.
