### ISSUE TITLE
Dramatically slows VSCode launch

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode-makefile-tools#361]
When this plugin is installed, then VSCode takes many more seconds to launch each time.

**Comment by bobbrow** [comment]
Hi there,

Can you run the `Developer: Startup Performance` command and share the output in the Extension Activation Stats section?

**Comment by andreeis** [comment]
@mcandre, an additional question, does that happen only when VSCode launches with opening a previous folder (which contains a makefile within or points to one via "makefile.makefilePath") or also if you launch VSCode without loading any folder?

**Comment by andreeis** [comment]
Closing old "more info needed" ticket. If this still happens please reactivate and provide more info so that we reproduce on our side.
