### ISSUE TITLE
This makes saving python files to take a long time to run...

### ISSUE THREAD

**Issue by alexbenfica** [microsoft/vscode-makefile-tools#362]
Type: <b>Bug</b>

This extension is causing this issue!
I found it doing the extension bisect.

https://github.com/microsoft/vscode/issues/90376

Extension version: 0.6.0
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Connection to 'SSH: vmlinux' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 3792)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|30.96GB (15.78GB free)|
|Process Argv|--crash-reporter-id 6d1dcd63-07d9-4b85-a2f6-73c35e15aa9d|
|Screen Reader|no|
|VM|80%|

Connection to 'SSH: vmlinux' could not be established  Canceled
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by bobbrow** [comment]
Can you provide more information that will help us reproduce the issue?  Is your workspace open source?  We don't see anything like this in the workspaces we've tried, but we also don't test the extension with python workspaces.  A couple of pieces of information that might help us are:
* The output from running the `Developer: Startup Performance` command
* Set the `makefile.loggingLevel` setting to `"Debug"`, run your scenario again, and share the output from the "Makefile tools" logger in the Output Window.

**Comment by alexbenfica** [comment]
Hi! I tried to simulate it again by re-enabling the extension but could not get it to happen again. Sorry by that.
