### ISSUE TITLE
command:makefile.getLaunchTargetArgsConcat makes all args into a single arg

### ISSUE THREAD

**Issue by tjswierzewski** [microsoft/vscode-makefile-tools#363]
I am trying to use launch.json to create a debug session. I am using this as opposed to the built in debugger launch because I would like to use the `setupCommands` field. The command substitution for `launchTargetPath` works great but when I use `getLaunchTargetArgsConcat` that program reads the arguments as one string with spaces.

the args line of my `launch.json` looks like this:
```
"args": [
                "${command:makefile.getLaunchTargetArgsConcat}"
            ]
```

I have also tried the 'getLaunchTargetArgs' commands but this throws an error that it does not return a string.

Any guidance on correct usage of these commands?

**Comment by gcampbell-msft** [comment]
@tjswierzewski Did this comment:  https://github.com/microsoft/vscode-makefile-tools/issues/363#issuecomment-1261312770, resolve your issue?
