### ISSUE TITLE
Cannot select launch target containing space in the binary name

### ISSUE THREAD

**Issue by audiovention** [microsoft/vscode-makefile-tools#373]
The title is mostly self-explanatory - my project's output binary has a space in the filename. Selecting it in the launch targets creates a launchConfiguration in settings.json which truncates the filename up to the space.

Until recently, I just tweaked the generated filename to include the part after the space, and everything worked fine. After a recent update though, the extension is not loaded at all if I have a launchConfiguration containing such space.

My complete settings.json file is as follows (certain names redacted):

```
{
    "makefile.makeDirectory": "Builds/LinuxMakefile/",
    "C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools",
    "makefile.configurations": [
        {
            "name": "Debug",
            "makeArgs": ["CONFIG=Debug", "-j14"]
        },
        {
            "name": "Release",
            "makeArgs": ["CONFIG=Release", "-j14"]
        }
    ],
    "makefile.launchConfigurations": [
        {
            "cwd": "/home/user/workspace/my-project/Builds/LinuxMakefile/build",
            "binaryPath": "/home/user/workspace/my-project/Builds/LinuxMakefile/build/My Application",
            "binaryArgs": []
        }
    ],
    "C_Cpp.default.intelliSenseMode": "linux-gcc-x64",
    "files.associations": {
        "*.mm": "cpp"
    }
}
```

**Comment by bobbrow** [comment]
Thank you for reporting this issue.  We will take a look.

**Comment by gcampbell-msft** [comment]
@audiovention I am currently trying to diagnose this issue and understand where the problem is happening. Could you give us some more information to help us diagnose?

1. Could you drop your makefile? Or maybe a simplified version that redacts any personal information?
2. Similarly, could you define `makefile.extensionOutputFolder`, `"makefile.loggingLvel" : "Debug"`, and `"makefile.extensionLog" : "extension.log"` in your `settings.json`, repro the issue, and then drop us the log files? This will help us reproduce the issue. 

Any other description of your issue and the steps you're taking to hit it would be appreciated in our attempts to repro and diagnose. Thanks!

**Comment by gcampbell-msft** [comment]
@audiovention Could you provide us with a snippet of the part of your makefile that specifies the binary with the space in the name? 

This would help us try and diagnose this issue.

**Comment by andreeis** [comment]
We tried with a repro on windows, we built a binary with space in its name which appeared fine in the launch target quickPick list and we selected it with no issues.
Alternatively, if it's not handy to share your project and makefile... share with us the dryrun.log. Same settings as @gcampbell-msft suggested above and you'll find "dryrun.log" in whatever you point "makefile.extensionOutputFolder" to.
Also, do you still reproduce the "extension is not loaded at all" part?

**Comment by audiovention** [comment]
Hi all, I've since migrated my project to cmake and don't use that extension anymore, however I'll try to generate a project that breaks it. FYI the project is generated with the JUCE framework

**Comment by andreeis** [comment]
Closing this ticket. Please reactivate if you see it happens again and provide additional info for us to repro, investigate and fix.
