### ISSUE TITLE
 module containing this breakpoint has not yet loaded on setting breakpoints

### ISSUE THREAD

**Issue by chim3ywangmo** [microsoft/vscode-makefile-tools#377]
Hello,

I have followed the tutorial (https://www.youtube.com/watch?v=cEC2iZCS2Lk) to enable debugging for Makefile project, which I have set up on Ubuntu machine. Although it is able to build and run well, when it comes to debugging it doesn't go beyond the main page. It shows the error, " module containing this breakpoint has not yet loaded on setting breakpoints". Additionally, when I set breakpoints in certain line, it debugs the later lines. Furthermore, I noticed that Makefile tool's configuration is defined as unset. 

Any suggestion regarding this issue would be truly helpful.

**Comment by bobbrow** [comment]
Were you able to get further on this?  I see you also opened #378.  Are these the same issue?
