### ISSUE TITLE
Cannot insert breakpoint 1

### ISSUE THREAD

**Issue by chim3ywangmo** [microsoft/vscode-makefile-tools#378]
Type: Debugger
ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run". Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x800ff20

Describe the bug
I have set up the project in the same manner as the tutorial on windows vscode with ssh remote to ubuntu. Initially, when I tried to debug I got the error as "Unable to start debugging. The value of miDebuggerPath is the invalid problem". I resolved the issue by inserting ("MIMode": "gdb", "miDebuggerPath": "/usr/bin") to makefile configuration. However, now I receive this error that I cannot insert a breakpoint. I have installed gdb 12.1 to the remote machine and also compiled with -g.

OS and Version: Windows (local machine), Downgraded to Ubuntu 20.04 (remote)
VS Code Version: 1.72.2
C/C++ Extension Version: 1.13.3
Other extensions you installed (and if the issue persists after disabling them): Makefile Tools

Any suggestion with regards to this would be truly appreciated.

**Comment by bobbrow** [comment]
Did the debugger start for you?  I expected that you would have to set the `miDebuggerPath` to the full path to the debugger, e.g.: `/usr/bin/gdb`.  I didn't think that worked with a folder.

Unfortunately, it looks like our implementation doesn't forward on any of the logging options for the debugger yet.  I think your best bet would be to create a new debug configuration using `launch.json` and using one of the [variables we support for substitution](https://github.com/microsoft/vscode-makefile-tools/blob/main/docs/makefile-settings.md) for the `program`.  You can also set properties like MIMode and miDebuggerPath if necessary.  Then use the `F5` key or the Debug panel to start debugging.

For example:
```json
{
    "configurations": [
        {
            "name": "Debug a",
            "type": "cppdbg",
            "request": "launch",
            "program": "${command:makefile.launchTargetPath}",
            "cwd": "${command:makefile.getLaunchTargetDirectory}",
        }
    ]
}
```

If you still have trouble after that, there is a `"logging"` property on the debug configuration that we can look at next and I'll loop in one of the engineers on the debugger team to help.

**Comment by chim3ywangmo** [comment]
Thank you so much, your suggestion helped me alot. I simply included launch.json and task.json and within the task.json I specified the location of makefile.
