### ISSUE TITLE
Error: Could not find one of 'package.json' manifest files in the package

### ISSUE THREAD

**Issue by kilitili62** [microsoft/vscode-makefile-tools#386]

**Comment by kilitili62** [comment]
Hello, I'm just trying to compile a Marlin firmware to obtain a.hex file but nothing works. I uninstalled several times but nothing worked.

**Comment by bobbrow** [comment]
Sorry, I don't really know how Mariln works, but it looks like they might have their own extension that can produce a build for you.  Perhaps you can give that a try if our extension is unable to build it for you.

**Comment by bobbrow** [comment]
https://marlinfw.org/docs/basics/auto_build_marlin.html

**Comment by andreeis** [comment]
@kilitili62 , we are closing this issue due to long time and no additional info, but please reactivate if this still happens and provide  context for us to investigate.
