### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hryamzik** [microsoft/vscode-makefile-tools#387]
- Issue Type: `Performance`
- Extension Name: `makefile-tools`
- Extension Version: `0.6.0`
- OS Version: `Darwin arm64 22.1.0`
- VS Code version: `1.73.1`

[ms-vscode.makefile-tools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-makefile-tools/files/10056983/ms-vscode.makefile-tools-unresponsive.cpuprofile.txt)

**Comment by andreeis** [comment]
@hryamzik, let us also have a look over the extension logs:
Set "makefile.loggingLevel": "Debug" and "makefile.outputFolder": "./LogsFolder" and "makefile.extensionLog": "LogsFolder/extension.log", then reload your project, let it configure and share with us "dryrun.log" and "extension.log" from "./LogsFolder".
If after waiting 1-2min you don't seem to see a message like "Configure succeeded" or "Configure finished", simply share these files as they are. There is a situation when "--dry-run" and "--always-make" together are causing some projects, depending on how their makefiles are written, to keep running configure targets. There are some imperfect workarounds that we can explore once we confirm it's the case.

**Comment by hryamzik** [comment]
[dryrun.log](https://github.com/microsoft/vscode-makefile-tools/files/10071794/dryrun.log)
[extension.log](https://github.com/microsoft/vscode-makefile-tools/files/10071795/extension.log)

I've also tried disabling this plugin and still get 100% CPU usage in this project.

**Comment by bobbrow** [comment]
These strings are likely the culprit:
```
+-------------------------------------------------+
```
We're planning to fix #106 next which should also address this.

**Comment by bobbrow** [comment]
The workaround for now is to remove strings with long sequences of hyphens `-----` in them.

**Comment by hryamzik** [comment]
It's not my project so I guess the workaround is to disable this extention.

**Comment by oraclejavanet** [comment]
Ran into the same issue. I had many `# ----------------------------` and `@echo "----------------------------"` lines in the Makefile. Removed them all which resolved the issue. Looking forward to the next fix. I want my lines back! :grimacing:

**Comment by gcampbell-msft** [comment]
This seems to have been fixed by #413
