### ISSUE TITLE
No makefile perspective

### ISSUE THREAD

**Issue by sayyadumar** [microsoft/vscode-makefile-tools#389]
@bobbrow 
This is my set up.
`xxx:~> uname -a `
`Linux atw-15-3-deumsay 5.3.18-150300.59.101-default #1 SMP Tue Nov 1 11:32:03 UTC 2022 (b2a976e) x86_64 x86_64 x86_64 GNU/Linux`

`code -v`
`1.73.1
6261075646f055b99068d3688932416f2346dd3b
x64`

`ms-vscode.makefile-tools version v0.6.0`

My Makefile in not in the "." but rather under "./build-Debug_Cross"

` {`
` "makefile.makeDirectory": "./build-Debug_Cross", ` 
` "makefile.makefilePath": "./build-Debug_Cross/Makefile", ` 
` "makefile.loggingLevel": "Debug" `
` } `

It shows up if I manually trigger "configure" with Ctrl+Shift+P and "configure". Setting **"makefile.alwaysPreConfigure": true** doesn't help either.

And one more thing I noticed is  using "${workspaceFolder}" "${workspaceRoot}" in the path doesn't parse.

**Comment by bobbrow** [comment]
This sounds like a bug.  The extension should activate when a Makefile is found anywhere in your folder.  If you enable logging with `makefile.loggingLevel` set to `"Debug"` does it give any hints as to why configuration doesn't start?  Is `makefile.configureOnOpen` set to `false` by chance?

Variable substitution will be done with #343.

**Comment by andreeis** [comment]
@sayyadumar, is your project open source or easy to share by any chance?
The output you shared, is that all? It looks like only a fragment from what we expect.
Is the Makefile present always at that location? It's not automatically generated later after you load your project in VSCode, correct?

**Comment by andreeis** [comment]
@sayyadumar, I am closing this ticket as it didn't have any update in a long time but please reactivate if you still see this happening and share more info to help us investigate.
