### ISSUE TITLE
Gopls mis-formatting for go-swagger

### ISSUE THREAD

**Issue by aparsapour** [microsoft/vscode-makefile-tools#399]
Type: <b>Bug</b>

Hi, 
I am using go-swagger for documenting my backend API, which is build on Golang & use of go-swagger.
The auto formating on save of my Go program text, is the issue. Specifically the required indentation of annotations/tags is not observed. this violated the swagger rules of yaml comments.

As follows you see the proper indentation (when the GO extension is disabled) . I have manually indented & is roughly accurate & works fine:
__________________________________________________
// swagger:operation POST /api/users/login Security Login
// login entrance
// ---
// parameters:
//   - name: request
//     in: body
//     required: true
//     type: object
**//     schema:
//         "$ref": "#/definitions/ReqBody"**
//
// responses:
 //   '200':
 //     description: response to login
 //     schema: 
 //       type: array
 //       items:
 //         "$ref": "#/definitions/UserIdentity"
 //   default:
//     description: unexpected error
//     schema:
//       "$ref": "#/definitions/UserIdentity"
func Login() {}
___________________________________________________

And when GO extension is enabled the formatter changes the indentation wrongly & result to error in generation of the spec file (swagger.yaml) . 
As follows see the mis-formatted text after saving!:
____________________________________________________
// swagger:operation POST /api/users/login Security Login
// login entrance
// ---
// parameters:
//   - name: request
//     in: body
//     required: true
//     type: object
**//     schema:
//     "$ref": "#/definitions/ReqBody"**
//
// responses:
//
//	'200':
//	  description: response to login
//	  schema:
//	    type: array
//	    items:
//	      "$ref": "#/definitions/UserIdentity"
//	default:
//	  description: unexpected error
//	  schema:
//	    "$ref": "#/definitions/UserIdentity"
func Login() {}
_____________________________________________________
the problem is on the line following line of the **schema:**tag,  which puts the **"$ref":**  at the same level as **schema:** tag

Thank you for your attention!

Extension version: 0.6.0
VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.29GB free)|
|Process Argv|--folder-uri file:///d%3A/go/sama-go --crash-reporter-id 53e5e4a0-d8a6-4f9f-a048-7ccde343801b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by bobbrow** [comment]
Hi there, this repository is for the Makefile Tools extension in VS Code.  You may want to try opening this issue in the repository for the GO extension.
