### ISSUE TITLE
Does Makefile Tools support aarch64-linux-gnu-gcc？

### ISSUE THREAD

**Issue by hongbolu** [microsoft/vscode-makefile-tools#400]
1、Does Makefile Tools support aarch64-linux-gnu-gcc？Where can I set the compile tools?
2、When I set
    "makefile.configurations": [
        {
            "name": "xxx",
            "makeArgs": ["CROSS_COMPILE=aarch64-linux-gnu-"]
        }
    ],
then the output is below：
 Unable to resolve configuration with compilerPath "aarch64-linux-gnu-gcc.exe".  Using "C:\mingw64\bin\gcc.exe" instead.

**Comment by bobbrow** [comment]
The error you are reporting is with the C++ extension trying to configure IntelliSense.  The next time you see this error, can you run the `C/C++: Log Diagnostics` command and share the output?

**Comment by andreeis** [comment]
@hongbolu , do you still reproduce this problem? Make sure you have the latest releases of both "Makefile Tools" and "CppTools". We will soon close this ticket unless we hear from you.

**Comment by hongbolu** [comment]
Thank you，I have solved this problem，this ticket can be closed。
