### ISSUE TITLE
makefile 

### ISSUE THREAD

**Issue by AyatallahAly** [microsoft/vscode-makefile-tools#404]
Make: not found 
Source: MakeFile tools(extension)

make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ make -f makefile dev
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command make -f makefile dev" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by bobbrow** [comment]
Is `make` in your %PATH% environment variable?  In other words, can you open a PowerShell or CMD window and run `make` without specifying the full path to it?

If not, please trying setting a value for the `makefile.makePath` setting which will tell us where the Make tool is.

**Comment by ISGNordicMNI** [comment]
> Is `make` in your %PATH% environment variable? In other words, can you open a PowerShell or CMD window and run `make` without specifying the full path to it?
> 
> If not, please trying setting a value for the `makefile.makePath` setting which will tell us where the Make tool is.

Does the extension install "make" or do you need to have anything installed previously for it to work. As replies and documentation says to reference the path to where "make" is, but no one is saying where make is located or giving examples to how you reference to it, nor if the extension installs it make or the extension is just a addition to VScode where you need to install "make" externally.

It's like inviting someone over and telling them to go get the flour in the cabinet, but there are 50 cabinets and in those cabinets there are 500 boxes where of the flour might be contained in. As if it was expected of me to go and get the flour and then place it in its box beforehand.

**Comment by syphex97** [comment]
> Is `make` in your %PATH% environment variable? In other words, can you open a PowerShell or CMD window and run `make` without specifying the full path to it?
> 
> If not, please trying setting a value for the `makefile.makePath` setting which will tell us where the Make tool is.

Does the extension install "make" or do you need to have anything installed previously for it to work. As replies and documentation says to reference the path to where "make" is, but no one is saying where make is located or giving examples to how you reference to it, nor if the extension installs it make or the extension is just a addition to VScode where you need to install "make" externally.

It's like inviting someone over and telling them to go get the flour in the cabinet, but there are 50 cabinets and in those cabinets there are 500 boxes where of the flour might be contained in. As if it was expected of me to go and get the flour and then place it in its box beforehand.

**Comment by bobbrow** [comment]
The extension does not install `make`.  It is usually installed with your compiler (in the same folder).  It doesn't have a standalone installer which is why we don't provide instructions on how to get it.

**Comment by syphex97** [comment]
> The extension does not install `make`. It is usually installed with your compiler (in the same folder). It doesn't have a standalone installer which is why we don't provide instructions on how to get it.

Awesome thanks.
The issue OP states is related to `make `not being installed previous to the extension

**Comment by andreeis** [comment]
@syphex97, I am closing this ticket since it looks that we answered all the questions. In case I overlooked something still left unaddressed let me know and feel free to reactivate.
