### ISSUE TITLE
Link from dependency to target

### ISSUE THREAD

**Issue by guettli** [microsoft/vscode-makefile-tools#405]
It would be nice if dependencies in Makefiles would be hyperlinks to the definition of the dependency.

Example:

![image](https://user-images.githubusercontent.com/414336/212030252-1633d7bf-21af-4682-abfd-3404cc8342a4.png)

"generate" (and "fmt" and "vet") should be hyperlinks to the corresponding definition in the Makefile.

**Comment by bobbrow** [comment]
Thank you for the feature request.  I think we have another issue tracking this (#208) so I will close this as a duplicate.  If that is incorrect, please add additional details to help us understand what else you would like to see with this feature.
