### ISSUE TITLE
Crash macOS!

### ISSUE THREAD

**Issue by jjm2473** [microsoft/vscode-makefile-tools#408]
This plugin creates tens of thousands of `make` processes on macOS, makes `fork` system call failed!

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/3896703/212607296-87308900-565d-4f98-a42c-8f1dfaa832cf.png">

<img width="365" alt="image" src="https://user-images.githubusercontent.com/3896703/212607413-e7a1d142-87fb-4b60-88c8-1a4b4cf5b6bf.png">

After disable this plugin and reboot VSCode, everything is back to normal.

**Comment by jjm2473** [comment]
Update: It can be reproduced in this project: https://github.com/jjm2473/openwrta

**Comment by bobbrow** [comment]
I didn't have a mac available, but did reproduce this on Ubuntu.  I don't have it fully configured to build this project, but was able to get past the infinite spawning of make by removing `--always-make` from the `makefile.dryrunSwitches` setting:

![image](https://user-images.githubusercontent.com/12818240/213314266-b62f776f-eaae-46d0-af84-76f92771c46d.png)

That switch works in most projects and makes sure that all the compiler commands are present, but it does not work well with this project for some reason.  You can experiment with it and see if it helps and you can also consult our [Troubleshooting Guide](https://github.com/microsoft/vscode-makefile-tools/blob/main/docs/troubleshooting.md).

If you find a combination of flags that works well, consider submitting a PR that edits our list repositories and shares the configuration that works best for it: https://github.com/microsoft/vscode-makefile-tools/blob/main/docs/repositories.md

**Comment by jjm2473** [comment]
Thank you for your reply! It fixed the issue after removing `--always-make` from the `makefile.dryrunSwitches` setting. Thanks again!
