### ISSUE TITLE
[Windows] Ampersand in path

### ISSUE THREAD

**Issue by KrestenHelstrup** [microsoft/vscode-makefile-tools#417]
Hi,

The extension does not correctly resolve paths with ampersand on windows systems.
Would it be possible to fix that in a future release ?

**Comment by andreeis** [comment]
@KrestenHelstrup, thank you for pointing this out. While investigating this, the fix turned to be quick so it will be included in the 0.7 release.

**Comment by KrestenHelstrup** [comment]
@andreeis - Sounds good. When is the expected release date of 0.7.0 ?

**Comment by andreeis** [comment]
@KrestenHelstrup, a fix for this will be released with 0.7 next week but if you would like to see how this works earlier you can install one vsix from [this link](https://github.com/microsoft/vscode-makefile-tools/actions/runs/4451312188).

go to the Extensions panel on the left
click "..."
run "Install from vsix" from the context menu

Let us know if you encounter any other issues or if you have any other suggestions/recommendations in this area of functionality.

**Comment by gcampbell-msft** [comment]
@KrestenHelstrup Due to 0.7.0 being available with this fix, we are closing this issue, please re-open if you hit issues.
