### ISSUE TITLE
make not found

### ISSUE THREAD

**Issue by pramodhreddy07** [microsoft/vscode-makefile-tools#422]

**Comment by andreeis** [comment]
@pramodhreddy07, fix is in testing, will be released with 0.7.

**Comment by andreeis** [comment]
@pramodhreddy07, we removed the popup notifications regarding makefile and make missing, we left the logging about that unchanged and we are also showing now the "C/C++" tab UI on the left side even when before it was hidden. In there we add now some extra elements about status on make/makefile/build.log: path where we search for them, if not found, you can click the edit pen icon to open settings and change this state via settings like "makefile.makefilePath", "makefile.makePath", "makefile.buildLog" and their "makefile.configurations[]" counterparts.

This will be released with 0.7 next week but if you would like to see how this works earlier you can install one vsix from [this link](https://github.com/microsoft/vscode-makefile-tools/actions/runs/4451312188).

go to the Extensions panel on the left
click "..."
run "Install from vsix" from the context menu

Let us know if you encounter any other issues or if you have any other suggestions/recommendations in this area of functionality.

**Comment by gcampbell-msft** [comment]
@pramodhreddy07 Since we have released the fix, we will close this issue. Please re-open if you run into issues!
