### ISSUE TITLE
keeps craching 

### ISSUE THREAD

**Issue by takotab** [microsoft/vscode-makefile-tools#429]
Type: <b>Bug</b>

Not sure how to reproduce but with this extretion active I keep getting the crashed 5 times within 3 minutes (or 3 times in 5 minutes) warning. 

Extension version: 0.6.0
VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|27, 24, 17|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 3a37dbc9-d21a-41ec-a330-15a29c1f3a44|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
pythonb192:30669360

```

</details>

**Comment by takotab** [comment]
Did the extension bisect. Based on that I concluded the problem was this extension, but with it disabeled it still crashes

**Comment by andreeis** [comment]
@takotab , what was crashing? VSCode? When you were loading one particular project or always or random? I hope you'll find the root cause and a solution quickly. If any other suspicions point towards the extension again let us know. Hopefully, the latest experiment with Makefile Tools disabled takes it off the table.
