### ISSUE TITLE
Not yet activated.

### ISSUE THREAD

**Issue by amira273** [microsoft/vscode-makefile-tools#440]

**Comment by andreeis** [comment]
@amira273, can you give more details? You do not see the "C/C++" left side UI that normally shows up when Makefile Tools extension gets activated?
We made some fixes in that area, that you can try by installing this private vsix from [this link](https://github.com/microsoft/vscode-makefile-tools/actions/runs/4451312188).

go to the Extensions panel on the left
click "..."
run "Install from vsix" from the context menu

If you still reproduce the problem with the vsix, then please write more details.
