### ISSUE TITLE
telemetry is sending, even it is disabled globally

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode-makefile-tools#446]
Hello. i see log:

Saving opened files before build.
Exception thrown during the configure process: Cannot read properties of undefined (reading 'ActiveClient')
**Sending telemetry: eventName = configure**
properties: firstTime = "false",makeDryRun = "true",readCache = "true",isClean = "true",processTargetsSeparately = "false",resetBuildTarget = "false",triggeredBy = "configure dirty (on open), settings (configureOnOpen)",buildTarget = "(unset)"
measures: numberBuildTargets = "0",numberLaunchTargets = "0",numberIndexedSourceFiles = "0",numberMakefileConfigurations = "0",totalElapsedTime = "0.668",exitCode = "-5"
Configure elapsed time: 0.668
Schema mismatch between settings and package.json for property "makefile.makefileDirectory"
**Sending telemetry: eventName = settings**
properties: makefile.loggingLevel = "Debug",makefile.makeDirectory = "undefined",makefile.makefilePath = "undefined"
Dropping various extension output files at /home/vdybala/.vscode-server/data/User/workspaceStorage/72c52b314a00e74617df8635ae0e8c61/ms-vscode.makefile-tools
Configurations cached at /home/vdybala/.vscode-server/data/User/workspaceStorage/72c52b314a00e74617df8635ae0e8c61/ms-vscode.makefile-tools/configurationCache.log
Deduced command 'make -C /nvm/work/prod_qt6_3/' for configuration "Default"
makefile.extensionOutputFolder setting changed.
makefile.configurationCachePath setting changed.
makefile.makeDirectory setting changed.
**Sending telemetry: eventName = settingsChanged**
properties: makefile.extensionOutputFolder = "undefined",makefile.configurationCachePath = "undefined",makefile.makeDirectory = "..."
Logging level: Normal
Dropping various extension output files at /home/vdybala/.vscode-server/data/User/workspaceStorage/72c52b314a00e74617df8635ae0e8c61/ms-vscode.makefile-tools
Configurations cached at /home/vdybala/.vscode-server/data/User/workspaceStorage/72c52b314a00e74617df8635ae0e8c61/ms-vscode.makefile-tools/configurationCache.log
Deduced command 'make -C /nvm/work/prod_qt6_3/' for configuration "Default"

but it is disabled globally:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/801951/229722420-8e410104-ec3a-48e4-9592-6842d8416a30.png">

It is rude to send telemetry even if I disable it explicitly. Please do not send it

Version: 1.77.0 (user setup)
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T10:02:16.981Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

Makefile tools: v0.6.0

**Comment by andreeis** [comment]
@dibalavs , thank you for letting us know about this. We'll have a look and address immediately.

**Comment by gcampbell-msft** [comment]
@dibalavs Thanks for the report! 

We depend on this npm package for sending telemetry: https://www.npmjs.com/package/@vscode/extension-telemetry, and it respects the users decision on whether to send telemetry or not. So, your telemetry is safe!

However, we will update our logging to avoid this confusion in the future. Thanks for notifying us!

**Comment by gcampbell-msft** [comment]
Completed in 0.7.0. Closing! 👍
