### ISSUE TITLE
Makefile Tools registers as a configuration provider too soon when it has no configurations to provide cpptools

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-makefile-tools#449]
Whenever the Makefile Tools extension activates, it appears to register itself as a configuration provider with the vscode-cpptools-api even when it has no configuration info to provide, which can cause other more valid configuration providers (i.e. CMake Tools) or sources of configuration to not be used and the user prompts to select an IntelliSense configuration source to not appear -- the C/C++ extension has code that will auto-use the 1st registered configuration provider (we're potentially thinking about improving that somehow). The repro is to just have a folder that contains an empty "makefile".

Ideally, it not register until it has a non-empty config, i.e. not
```json
Custom browse configuration: 
{
    "browsePath": [],
    "compilerArgs": []
}
```

**Comment by gcampbell-msft** [comment]
@sean-mcmanus Thanks for letting us know. I'll look into reproducing and then fixing. Thanks!

**Comment by sean-mcmanus** [comment]
Maybe our extension can just ignore an empty browse.path when we encounter it and stop using that configuration provider, in particular, because it can cause compile_commands.json to not be auto-detected for a potential configuration source.

**Comment by gcampbell-msft** [comment]
Completed in 0.7.0 , closing.
