### ISSUE TITLE
Exception thrown in output terminal related to Regex

### ISSUE THREAD

**Issue by rali7196** [microsoft/vscode-makefile-tools#468]
Small issue that is just a little annoying to deal with. Basically, everytime I open VSCode in WSL, I notice that everytime I open a C file in my current workspace my terminal automatically changes to the "output" section and gets this output. 

![image](https://user-images.githubusercontent.com/97213257/235568755-47a2f3d1-d495-4181-92bc-2bfbf9246410.png)
![image](https://user-images.githubusercontent.com/97213257/235568794-30f68c9e-979a-4f12-a2b5-f707d01f54fa.png)

Please reply with any questions you might have, first time making an issue on Github so let me know if anything else is needed.

**Comment by andreeis** [comment]
@rali7196, did you notice that this started happening with 0.7.0 or not necessarily?
Please set "makefile.loggingLevel": "Debug", "makefile.extensionOutputFolder": "./MyOutputFolder" (or something else), "makefile.extensionLog": "extension.log", then reload your project, let it configure until the end (see "configure finished" in the output channel), then open one such c/c++ source file for which this error reproduces and after all this share with us "dryrun.log" and "extension.log" from ./MyOutputFolder.

**Comment by rali7196** [comment]
@andreeis Thank you for your fast response. Here are the logs you requested:
Dryrun.log:
![image](https://user-images.githubusercontent.com/97213257/236360683-b783504e-e73d-42fd-9570-037f9e326ce9.png)
extension.log:
![image](https://user-images.githubusercontent.com/97213257/236360714-717431fc-ea66-4169-833b-0e259f36e92f.png)
![image](https://user-images.githubusercontent.com/97213257/236360732-d990cf4a-2415-4e36-b573-eb769e9af44d.png)

**Comment by rali7196** [comment]
Also, I'm not entirely sure when I started seeing this bug, but I just started using Makefile tools if 0.7.0 is a recent version

**Comment by rali7196** [comment]
Ended up being a configuration issue on my part, feel free to close this

**Comment by andreeis** [comment]
@rali7196 , glad to hear that you are unblocked and that this wasn't a long term issue.
