### ISSUE TITLE
Repro project does not build

### ISSUE THREAD

**Issue by orkunsystems** [microsoft/vscode-makefile-tools#470]
Does Makefile Tools support Windows 11 with minGW？

**Comment by andreeis** [comment]
@orkunsystems , yes, MinGW and WSL as well. Let us know if you encounter any issue setting up your project in VSCode.

**Comment by orkunsystems** [comment]
Hi Andreea,

I thank you very much for your quick response. I have been trying to implement a project during the last week, but I could not somehow get the project compiled fully. It links without compiling. Initially, I had one rule for compiling and linking. I had to change it after I got error message from the compiler. Now I have two rules : one for compiling and one for linking. It seems that it did not help, but the compiler stopped error message.

I tried to find some examples/information on the net , but I could not find a mentionable example for Windows. All the resources I found are related to Linux and I decided to post a question, if Windows were supported.

Would it be possible to get some information/example or any link that provides some orientation?

I thank you very much again.

Regards,
Berat

**Comment by andreeis** [comment]
@orkunsystems, so it's not like you already have a project that exists and now you want to start using the extension and you want to configure your project to work for VSCode and Makefile Tools. You are writing the project now and you need some help writing the makefile? We have experience configuring projects to be used in the context of VSCode and Makefile Tools once the projects are built and working fully end to end in a terminal, with a developer experience already setup.
Or maybe I understand wrong what is needed here. Either way we are more than happy to help with anything.
Do you have a public repository we can look at? Easy to package the project to send our way? Before even writing a makefile, do you have a sequence of compilation/linking commands that already work or you are exploring for the right commands needed for your source code? You could share your source code.

**Comment by orkunsystems** [comment]
Andreea,

I thank you very much for your follow-up and efforts to help me.

I have indeed a project. However, it is tiny (part of a bigger project). I am using this small project to learn the makefile-tools and makefile as a whole because I am intending to use it in my next project.

I made a zip file and I am enclosing it with his email. There is also a read-me file in the zipped package, which gives more information.

In the case of minGW and it is products, they are completely installed and paths are updated. I can confirm that it is working completely and I am currently using it with Cmake.

I should also mention that I am looking forward to uninstalling Cmake from my machine. 😲

I am so exited and looking forward to hearing from you.

I thank you very much again.

Have a nice day.

Enclosure: TestMakefile.zip

**Comment by orkunsystems** [comment]
Hi!

The current test does not cover packages glm and vulkan. It will only evaluate glfw. I made slight changes in the main.cpp such that the code now covers all three packages.

I am sending the new main.cpp with this email. Would you please consider replacing it?

I have anxiously been waiting for the result. 😊

Have a nice day!

Enclosure: main.cpp

**Comment by andreeis** [comment]
@orkunsystems , we were not able to try the project you attached but we are doing a one pass now through all the tickets opened in our repository. Quick question: since then, were you able to get unblocked? Do you still need us to look into this? Thank you.
