### ISSUE TITLE
Permission denied error when pre-configure script is run on a shared Linux environment

### ISSUE THREAD

**Issue by ryan-phillips** [microsoft/vscode-makefile-tools#475]
When multiple users on a shared Linux environment use the `makefile.preConfigureScript` setting, the following error appears in the output:

    /tmp/wrapPreconfigureScript.sh: line 2: /tmp/wrapPreconfigureScript.out: Permission denied

Furthermore, "Makefile: Pre-Configure" will sometimes run a pre-configure script created by a different user, since `/tmp/wrapPreconfigureScript.sh` can only be overwritten by the user who first created it.

Other extensions put temporary files in the path of the XDG_RUNTIME_DIR environment variable, when it is set. Currently, '/tmp' is hard-coded here:

https://github.com/microsoft/vscode-makefile-tools/blob/7b3cc9f1d002615bac9fa4429e46c24cff3debe5/src/util.ts#L93

**Comment by andreeis** [comment]
@ryan-phillips , thank you for the suggestion. We did not realize this situation and also I wasn't familiar with the XDG_RUNTIME_DIR environment variable on linux. Easy fix, we'll get it in the next 0.8.0 release.
