### ISSUE TITLE
How to add a different makefile file name

### ISSUE THREAD

**Issue by bwm-projects** [microsoft/vscode-makefile-tools#480]
I am trying to find out if the makefile extension supports adding different Makefile file names.  It looks like it only supports the file names Makefile or makefile.   I searched the configuration settings and online docs but didn't see anyway to do this.  I have a build environment that calls different makefiles based on the Linux platform (for building package installer files).  For example: "Makefile.debian" using -f make command option.   Can I add an entry to the settings.json file for recognizing different makefile filenames?

**Comment by picchi-lucas** [comment]
You can use `"makefile.configurations"` setting in `settings.json`

Example:

```json
    "makefile.configurations": [
        {
            "name": "Default",
            "makefilePath": "Makefile"
        },
        {
            "name": "Debian",
            "makefilePath": "Makefile.debian"
        },
        {
            "name": "Ubuntu",
            "makefilePath": "Makefile.ubuntu"
        },
        ...
    ],
```
![imagen](https://github.com/microsoft/vscode-makefile-tools/assets/97546801/eb174caa-dbed-4cea-8259-d585daae7526)

**Comment by gcampbell-msft** [comment]
@bwm-projects Thanks for your question! I think that @picchi-lucas suggestion is the best one, other than that suggestion, I don't believe Make itself allows for modifying what the name of the file is. 

Please let us know if that suggestion works for you, and if so, we can close the issue!

**Comment by andreeis** [comment]
About syntax coloring, currently the Makefile Tools extension does not have any "makefile language services" features implemented. A future release will bring that at some point.
About about using the differently named makefile or not, you can confirm by setting 
"makefile.loggingLevel": "Debug",
"makefile.extensionOutputFolder": "./MyOutputFolder",
"makefile.extensionLog": "extension.log"

If you read (and share with us too) from ./MyOutputFolder the files dryrun.log and extension.log, we can see which makefile is being used exactly.

**Comment by andreeis** [comment]
@bwm-projects, there is an advice I did not realize to give last time I replied. In order to benefit from the already built in VSCode colorization basic support for the Makefile language (which we did not contribute to but plan to extend on top of in future) you can associate your differently named makefile files with the makefile language via the setting "files.associations".
Like you can see explained in [this question/answers link](https://stackoverflow.com/questions/42624115/how-do-i-config-visual-studio-code-to-open-mak-file-as-makefile).

**Comment by andreeis** [comment]
I am closing this ticket since we answered all the questions posted here but please reactivate if anything doesn't seem to function as we describe.

**Comment by FFdhorkin** [comment]
> About syntax coloring, currently the Makefile Tools extension does not have any "makefile language services" features implemented. A future release will bring that at some point

Is there a ticket tracking this?

**Comment by gcampbell-msft** [comment]
@FFdhorkin I don't believe so, feel free to create one, detailing what services you're interested in. Thanks!
