### ISSUE TITLE
quotation escape bug

### ISSUE THREAD

**Issue by HillalRoy** [microsoft/vscode-makefile-tools#497]
It's compiling but vscode showing error `unrecognized token`
```makefile
CFLAGS = -DA_LOG_DOMAIN=\"myapp\" 
```

```
unrecognized token C/C++(7)
---
#define a_debug(__VA_ARGS__...) a_log (A_LOG_DOMAIN, A_LOG_LEVEL_DEBUG, __VA_ARGS__)
Expands to:

a_log (\"myapp\", A_LOG_LEVEL_DEBUG, ...)
```

**Comment by zhykzhykzhyk** [comment]
already described in #465

my workaround was `-D 'VAR="str"'`

**Comment by gcampbell-msft** [comment]
@zhykzhykzhyk Thanks for describing the fix! Closing this issue thanks to the resolution.

**Comment by zhykzhykzhyk** [comment]
> @zhykzhykzhyk Thanks for describing the fix! Closing this issue thanks to the resolution. 

I think a real fix is needed, as changing all existing makefiles to the only format that this extension can handle isn't a great idea

**Comment by gcampbell-msft** [comment]
@zhykzhykzhyk This is good feedback, we'll track this in #465. Please upvote that issue and maybe even follow up again on that issue so that we can make sure to prioritize it correctly. Thanks!

**Comment by HillalRoy** [comment]
Every time Makefile is generated I have to modify the Makefile it's very annoying
