### ISSUE TITLE
One time warning about possible commands being run via --dry-run

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#506]
Even if the workspace is trusted, when a project is loaded in VSCode and we invoke "make --dry-run", most of the times the commands are only displayed and not run but because of the following exceptions we should warn the users, never allow directly a --dry-run to be performed until the user allows or silences the popup.
- --always-make combined with --dry-run may generate makefiles to be rewritten, configure targets to be run and actually cause a very annoying infinite loop (with various side effects to the repository)
- $shell command constructs in the makefile are actually run even in --dry-run mode
- recursive calls to make lose the --dry-run, resulting in real build happening versus simulation

**Comment by jasonmp85** [comment]
This error message is _very_ confusing. I had no clue what I was being asked and the first many times understood it to say _Hey, VS Code is configuring this project, but you can still run code using `--dry-run` if you wish_

  - Is it actually _Configuring project_? That's a progressive verb, leading readers to believe something is happening in the background. My guess is it means it is _in_ some configuration flow and needs input
  - Why is `--dry-run` relevant at all? This is unexplained, and there are no buttons for more information. Is VS Code going to run things in `--dry-run` without me asking? Or is this just informing me of a side-effect possible in `make`, a tool my project is, definitionally, already using?
    - If the former (VS Code is warning me it will automatically run `make` with `--dry-run` for some reason and I need to confirm my `Makefile` has no side effects, then **ask that**
  - My present interpretation, after finding this ticket, is it's literally just telling me about `make` behavior? It should probably read something like "It is possible for `make` to have side-effects even when `--dry-run` is provided. Enable Makefile extension for this project?"

**Comment by jasonmp85** [comment]
Oh, and uh, _Configure_ is a particularly bad verb to use in this space. I did a double-take on a few projects thinking "configure what? I don't have `./configure`"

**Comment by jasonmp85** [comment]
Ok, I found this _waaaay_ back in my _Output_ pane, and it's much better! Unfortunately, everyone's attention is going to go to the notification with an error icon in its upper-left, not the tool text scrolling by. If the error could be rewritten to give a summary of this, it might be best

> The Makefile Tools extension process of configuring your project is about to run 'make --dry-run' in order to parse the output for useful information. This is needed to calculate accurate IntelliSense and targets information. Although in general 'make --dry-run' only lists (without executing) the operations 'make' would do in the current context, it is still possible some code to be executed, like `$(shell)` syntax in the makefile or recursive invocations of the `$(MAKE)` variable.

**Comment by gcampbell-msft** [comment]
@jasonmp85 Thanks for your comments, investigation, and feedback! Though you found the answer to your questions, you bring up a good point about whether the pop-up is misleading. I'll create a new issue from your comments and add it to our backlog.

**Comment by DoctorHayes** [comment]
Is there a way to disable this notification in all projects? I click "Yes (don't show again)" but it still asks me for every other folder I open.

**Comment by gcampbell-msft** [comment]
@DoctorHayes What OS are you using? We've gotten one other issue where a user is facing this issue, and I have a suspicion that something is going on in Mac machines with our implementation. Thanks!

**Comment by DoctorHayes** [comment]
> @DoctorHayes What OS are you using? We've gotten one other issue where a user is facing this issue, and I have a suspicion that something is going on in Mac machines with our implementation. Thanks!

I am using Ubuntu under WSL.

**Comment by gcampbell-msft** [comment]
@DoctorHayes Understood, thanks for the information. If you could follow up with your experience on this issue as well: #547, that would be great. 

Thanks!

**Comment by SecureFlag-Aedan** [comment]
I would also be curious to know where this setting is stored as when running on a docker container I export all my vs code config and yet every boot it still shows the pop up as if it is the first boot.

**Comment by ilude** [comment]
FYI: I'm seeing this inside devcontainers running python:3.12-slim-bookworm

**Comment by gcampbell-msft** [comment]
@ilude Please update to the pre-release version, this warning is removed from the product in pre-release. Thanks!
