### ISSUE TITLE
Problems with debugging

### ISSUE THREAD

**Issue by King-Z-101** [microsoft/vscode-makefile-tools#525]
The program runs the test target fine but if I set a breakpoint at the start of main() but it doesn't stop. 

Makefile:
CC = gcc

CFLAGS = -Wall -g

LD = gcc

OBJS = htable.o 

all: htable

htable: htable.o 
	$(CC) $(CFLAGS) -o htable $(OBJS)

test: all
	echo Testing all
	htable < test1
	
	echo done.

clean:
	rm *.o 
	rm htable

ScreenShot:
![image](https://github.com/microsoft/vscode-makefile-tools/assets/111461124/61737b00-e09d-4bc8-b1e4-22f787e74864)

**Comment by gcampbell-msft** [comment]
@King-Z-101 Are you able to debug the file if you set up a manual launch.json? This may help us diagnose if it's an issue with the vscode-cpptools debug part of the extension or if it's an error in how we attempt to configure debugging. 

Any information you can provide would be very helpful, thanks!
