### ISSUE TITLE
Preconfigure arguments doesn't work

### ISSUE THREAD

**Issue by 156898293** [microsoft/vscode-makefile-tools#531]
when lunching preconfigure script via makfile tools the "preConfigureArgs": [" arg2 "] option seems to be ignored.

[makefile_precfg.zip](https://github.com/microsoft/vscode-makefile-tools/files/13417218/makefile_precfg.zip)

**Comment by gcampbell-msft** [comment]
I believe #530 will fix the issue. We were incorrectly not putting space between the first argument and the command file. Feel free to pull down the code for that PR and try it, or wait until the pre-release channel has the fix. Thanks!

**Comment by 156898293** [comment]
Ok. I'll wait for next version available in the  pre-release channel and report back.

**Comment by 156898293** [comment]
Just out of curiosity. you mentioned adding a space should solve the problem...
is this the change you had in mind?
"preConfigureArgs": [ "arg1" ],
=>
"preConfigureArgs": [ " arg1" ],
If so it doesn't help for my v0.8.16. I still get no args into my script.

**Comment by gcampbell-msft** [comment]
@156898293 Ah, thank you for the follow-up, the suggestion I made definitely fixes a bug, but it might not be the bug you were hitting. I'll pull down your zip file and test right now. Thanks!

**Comment by gcampbell-msft** [comment]
@156898293 Could you post a screenshot of your issue? Also, what OS are you running? Is this on Windows? Linux? Thanks.

**Comment by 156898293** [comment]
The minimal project and description is above. I just pass arguments to my pre-cofigure scripts and in the script I print number of arguments as "argc #"
I run vscode on windows, but use ssh host to virtual-ubuntu.
If you want I can give you access to my PC via teams meeting for debug purpose.

**Comment by gcampbell-msft** [comment]
@156898293 OH, I think I found the issue, it was a silly bug on my part (assuming I'm correct). 

Could you install this vsix and test for me? You'll need to download it, then rename the download to makefile-tools.vsix. You can then install that vsix directly by doing the following:

![image](https://github.com/microsoft/vscode-makefile-tools/assets/86264750/7f0cfc82-5b6c-48dd-91e8-21cc39177dd9)


[makefile-tools.zip](https://github.com/microsoft/vscode-makefile-tools/files/13427498/makefile-tools.zip)

**Comment by 156898293** [comment]
working on it

**Comment by 156898293** [comment]
It definitelly behavies differently. However it is still not working...

err: /tmp/wrapConfigureScript.sh: line 1: /home/xxxx/proj/preconfig.sh  arg2 : No such file or directory

Full log
==========
Pre-configuring...
Script: "/home/xxxx/proj/preconfig.sh"
/tmp/wrapConfigureScript.sh: line 1: /home/xxxx/proj/preconfig.sh  arg2 : No such file or directory
The pre-configure script returned success code but somewhere during the preconfigure process there were errors reported. Double check the preconfigure output in the Makefile Tools channel.
Sending telemetry: eventName = preConfigure
properties: exitCode = "-5",triggeredBy = "command pallette (preConfigure)"
measures: preConfigureElapsedTime = "0.014"

**Comment by gcampbell-msft** [comment]
@156898293 I appreciate you helping me test this, as I don't currently have a readily available linux machine so it would take more time for me to test. I have one more thing that would be helpful to test:
[makefile-tools.zip](https://github.com/microsoft/vscode-makefile-tools/files/13427700/makefile-tools.zip)

Follow the same steps as before.

**Comment by 156898293** [comment]
Ok I made sure I installed the correct .vsix and the output is the same as above...
![image](https://github.com/microsoft/vscode-makefile-tools/assets/150666439/047daf68-0490-4097-840c-bed4bcedead5)

**Comment by gcampbell-msft** [comment]
@156898293 Again, thank you for testing so quickly. I have what should definitely be the fix.

Originally the issue was that we weren't handling the script arguments on linux. Then the issue was that I was improperly quoting the items of the script such that it was treating the args as part of the filepath, now, it should be fixed.

[makefile-tools.zip](https://github.com/microsoft/vscode-makefile-tools/files/13427996/makefile-tools.zip)
