### ISSUE TITLE
Typo in README "makefile.preConfigureSript"

### ISSUE THREAD

**Issue by TCWORLD** [microsoft/vscode-makefile-tools#548]
I didn't know whether you'd rather this be added as an issue, or to have just made a PR to fix it but...

In the README, [third section](https://github.com/microsoft/vscode-makefile-tools#pre-configuring-your-project), it states a configuration setting of `makefile.preConfigureSript`. This should be `makefile.preConfigureScript` (note the missing `c` in `Script`).

**Comment by gcampbell-msft** [comment]
Ah, good catch! I'm happy to take a PR from you to fix this! However, I'll get to it sometime this week if you don't have time. 

Thanks!

**Comment by gcampbell-msft** [comment]
This issue was fixed in #549. Thanks!
