### ISSUE TITLE
[i18n] French: dry-run parameter translated

### ISSUE THREAD

**Issue by cvergne** [microsoft/vscode-makefile-tools#550]
Hi,

The `--dry-run` parameter is wrongly translated in french (I haven't checked in other languages) to `--essai à sec`, which is pretty funny but should not be translated :D 

I opened an issue instead of a PR as I'm not sure if i18n files are managed from an outside tool.

https://github.com/microsoft/vscode-makefile-tools/blob/1e8c857e3eb73cc0d39441ce7c452d2b2e6dfec0/i18n/fra/src/make.i18n.json#L22

Thanks :)

**Comment by gcampbell-msft** [comment]
@cvergne Thanks for pointing this out. I've created an internal ticket and will track the progress to ensure it gets fixed, thanks!
