### ISSUE TITLE
how to use this when develop server is in docker

### ISSUE THREAD

**Issue by arnold0kang** [microsoft/vscode-makefile-tools#551]
hi, I use vscode in window, but my develop server is ubuntu in docker . when i install this extension for my remote ssh project . this extension stay in installing , stuck here. what should I do ?  I have search in google . maybe caused by no port export for this. but the doker only forward port 22. thanks

**Comment by xiahualiu** [comment]
If you used the Dev Container extension I believe all you need to do is just connect to the docker container using that extension then do everything just like you would do on your local machine.

VSCode->ssh remote connection->switch workspace folder->reopen in container(now you are in the container env)

You need to write a `devcontainer.json` file for your docker image and put it inside `.devcontainer` folder under your workspace in step 3.

You don't need to port forward.

**Comment by gcampbell-msft** [comment]
@xiahualiu Thanks for the great suggestion! @arnold0kang Please let us know if this works for you
