### ISSUE TITLE
Warning about possible commands being run in --dry-run is misleading and confusing

### ISSUE THREAD

**Issue by gcampbell-msft** [microsoft/vscode-makefile-tools#562]
This error message is _very_ confusing. I had no clue what I was being asked and the first many times understood it to say _Hey, VS Code is configuring this project, but you can still run code using `--dry-run` if you wish_

  - Is it actually _Configuring project_? That's a progressive verb, leading readers to believe something is happening in the background. My guess is it means it is _in_ some configuration flow and needs input
  - Why is `--dry-run` relevant at all? This is unexplained, and there are no buttons for more information. Is VS Code going to run things in `--dry-run` without me asking? Or is this just informing me of a side-effect possible in `make`, a tool my project is, definitionally, already using?
    - If the former (VS Code is warning me it will automatically run `make` with `--dry-run` for some reason and I need to confirm my `Makefile` has no side effects, then **ask that**
  - My present interpretation, after finding this ticket, is it's literally just telling me about `make` behavior? It should probably read something like "It is possible for `make` to have side-effects even when `--dry-run` is provided. Enable Makefile extension for this project?"

_Originally posted by @jasonmp85 in https://github.com/microsoft/vscode-makefile-tools/issues/506#issuecomment-1947191752_

**Comment by gcampbell-msft** [comment]
@jasonmp85 ended up finding the answer to his questions: https://github.com/microsoft/vscode-makefile-tools/issues/506#issuecomment-1947218152, but the possible issue still stands about the pop-up being misleading.

**Comment by MightyCreak** [comment]
I was confused as well, especially because I didn't know that `make` had a `--dry-run` command-line option.

**Comment by gcampbell-msft** [comment]
@MightyCreak We have merged #573 and it should be available in pre-release within the hour.

**Comment by MightyCreak** [comment]
Thanks! And thank you for the heads up!

**Comment by jasonmp85** [comment]
Thanks for the resolution! Reporting this felt minor, but I'm glad to see the attention to user-experience here!

**Comment by Yingzi1234** [comment]
Happy to see your issue has been resolved, thanks for contributing to Developer Community.
