### ISSUE TITLE
Write up a document about configuration and projects that we know work.

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-makefile-tools#57]

**Comment by submatrix** [comment]
Just wanted to chime in and say that @andreeis step #2 in the comment above worked for me. I was simply looking for a way to pass an argument to make ("-j8" in my case), but I couldn't figure out the proper syntax for the makefile.configurations in the settings.json file after reading the readme. Using the sample code provided I was able to set the configuration to "MyConfig". the Build target to "all", and I confirmed that "-j8" was passed to the make command successfully:

```
Building the current target. Command: make all -j8
make: Nothing to be done for 'all'.
Target all built successfully.
```

Thanks!
