### ISSUE TITLE
As a C developer I want to run ./configure with options first so that make only build what is needed

### ISSUE THREAD

**Issue by rvanlaar** [microsoft/vscode-makefile-tools#58]
Thanks for the invitation to this repository.

I do most of my C coding for scummvm: https://github.com/scummvm/scummvm/.
In my case I want to run `./configure --disable-all-engines --enable-engine=director` to only have scummvm build the 
part of the program I develop on.  This makes the binary smaller by 111 MB that is a 90% size reduction.

I would be great if quick options are available for this. Sometimes I need to run a full build, i.e. `./configure` and other times
I need to add an address sanitizer: `./configure --enable-asan`.

**Comment by gcampbell-msft** [comment]
Closing this due to it's age and having very little activity. @rvanlaar Please open a new issue if you still are having issues or have any feature requests for us to consider. Thanks!
