### ISSUE TITLE
[Flaky] The "modify target" window is empty when setting the "Launch target"

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-makefile-tools#587]
**More info:**
1. This issue is only reproduced on Windows platform
2. Reproduction rate of 60%
3. This issue is not a regression bug

**Repro steps:**
1. Open VScode  and clone the repo [makefile-example](https://github.com/remonbonbon/makefile-example)
2. Open Makefile and click "Makefile: Set the make launch configuration" to set the target

**Expected result:**
It should appear to correspond to the target 
![image](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/e46dd37a-a139-4466-9a00-3e4e37af0fb5)

**Actual result:**
It doesn't appear to have a corresponding target 
![image](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/4f3e94ec-d25f-419b-81e4-1f0ba542515e)

**Comment by gcampbell-msft** [comment]
Since this is a flaky issue and you can retry the launch target dropdown, I'm going to close this. Thanks!

**Comment by Yingzi1234** [comment]
@gcampbell-msft Git it! Thank you for your help!
