### ISSUE TITLE
Clicking anywhere on the "Launch Target" line will bring up the "modify target" Window

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-makefile-tools#588]
**More info:**
1. This issue is reproduced in all three platforms(Windows, Linux, Mac)
2. This issue is not a regression issue

**Repro steps:**
1. Open the Makefile UI
2. Click anywhere on the "Launch target" line

**Expected result:**
It should not pop up the "modify target" window. The window should only appear after clicking the "Makefile: Set the make launch configuration" button

**Actual result:**
Clicking anywhere on the “Launch Target“ line brings up the "modify target" Window
![Question4](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/4e808706-c40d-403a-8f6b-844ff0d02dcb)

**Comment by gcampbell-msft** [comment]
Fixed, please confirm @Yingzi1234 in the pre-release once it's release. Thanks!

**Comment by Yingzi1234** [comment]
@gcampbell-msft Thanks for your help, I'll verify this on the 0.10.0 version once it's released.

**Comment by Yingzi1234** [comment]
@gcampbell-msft This issue has been fixed on latest version, you can get the details below.

ENV:
VSCode: 1.89.1
Makefile tools: v0.10.9(pre-release)
C/C++: v1.20.5

![588](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/b882bb40-d769-4377-9f9c-415ab73840eb)
