### ISSUE TITLE
Implicit system include directories not included in browsePath

### ISSUE THREAD

**Issue by EricHripko** [microsoft/vscode-makefile-tools#59]
# Overview
My project uses [Red Hat's DTS](https://developers.redhat.com/products/developertoolset/overview) in order to build. This means that some include directories are implicit:
```
$ cpp -v /dev/null -o /dev/null
Using built-in specs.
Target: x86_64-redhat-linux
...
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 
...
#include "..." search starts here:
#include <...> search starts here:
 /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include
 /usr/local/include
 /opt/rh/devtoolset-7/root/usr/include
 /usr/include
End of search list.
...
```
Judging by [this StackOverflow](https://stackoverflow.com/questions/4980819/what-are-the-gcc-default-include-directories), it appears to be a common thing with GCC.

Due to the above, my `Makefile` does not explicitly specify the system include directories. This misleads the extension to ignore the system include paths (see excerpt from `configurationCache.log`):
```
                        "includePath": [
                            "/workarea/exmpllogic",
                            "/opt/bb/include/"
                        ],
```

As a result, autocompletion/syntax checking breaks on system includes:
![Error](https://user-images.githubusercontent.com/707679/96999508-2990d000-152d-11eb-9b56-d2403196ea97.png)

# Expected behaviour
System includes are detected by the extension and are automatically picked up by auto-complete/syntax checking. This mirrors the behaviour of what I see today with _CMake Tools_ extension.

# Actual behaviour
System includes aren't detected by the extension and the user has to manually specify `-I/usr/local/include -I/usr/include ...` for auto-complete/syntax checking to work correctly.

**Comment by EricHripko** [comment]
Thanks for all the extra information 👍 I've dug into this deeper and found 2 (somewhat related) causes for this:
- I have several Makefiles that live in their own subdirectories of the project (one for the local library, one for the service, one for tests etc.)
- Makefiles expect to be called from within the subdirectory, not the project root
- I've hacked this to work by including `-C exmpllogic/` in `makeArgs`, but this occasionally confuses the extension; for example, on save I get the following error message:
```
Deduced command 'make ... -C exmpllogic/ -f libexmpllogic.mk' for configuration libexmpllogic.mk
The makefile entry point was not found. Make sure it exists at the location defined by makefile.makePath or makefile.configurations[].makePath or in the root of the workspace.
```
- Since I have several Makefiles, I need to remember to go into `Makefile` extension and change the active _Configuration_ when I'm switching between files of library/service/tests

The IntelliSense false report above was because I've forgotten to switch the active configuration, which made sources files of library fall back to default IntelliSense settings and fail. Therefore, the immediate issue at hand can be considered resolved. Would you like me to create any separate issues for some of the hurdles described above?

**Comment by andreeis** [comment]
I didn't focus much on the -C scenario, there are some bugs there that we'll be fixing. Share me your exact configurations snippet from settings and the log related to that in the output channel (is there '...' part of the deduced command?)

Also, try to wrap all your makefiles under one makefile the root to have all available at once.

**Comment by EricHripko** [comment]
Sorry for the delay in getting back to your @andreeis. The configuration is below:
```jsonc
        {
            "name": "libexmpllogic.mk",
            "makefilePath": "libexmpllogic.mk",
            "makeArgs": [
                //...
                "-C exmpllogic/",
            ],
        },
```
Here and in the snippet earlier, `...` represents a bunch of make variables in the form of `VARNAME=VALUE`. These are necessary for my `Makefile` to function correctly. I am afraid I cannot share the exact list of these variables since they refer to proprietary IP.

> Also, try to wrap all your makefiles under one makefile the root to have all available at once.

I would love to do that, but, unfortunately, the `Makefile`s are very complex and cannot be combined into one. That's why the workflow for such projects typically is "go into a directory with library/binary/test suite, run `make`".

**Comment by andreeis** [comment]
I'll play more with the -C and -f scenarios to reproduce the error on save that you mentioned, but before that, regarding wrapping your makefiles into one in the root folder, let me know if this helps:
    ${MAKE} VARNAME=value -C exmpllogic1 -f libexmpllogic1.mk
    ${MAKE} VARNAME=value -C exmpllogic2 -f libexmpllogic2.mk
    ....

Understanding your scenario, I'm brainstorming how to support this better in the extension so that you wouldn't need these workarounds.

**Comment by andreeis** [comment]
If the wrapping above won't work, there's still something better than always switching configurations. In your usual terminal, build all those folders and save all the build outputs in one file in the root folder, let's say fullBuild.log and set makefile.buildLog to that. The extension will not invoke make anymore and will parse everything that's needed from that file.

**Comment by EricHripko** [comment]
I've updated the configuration to be like this (removing `makefilePath` and using `-f`) and it seems to work perfectly:
```
        {
            "name": "libexmpllogic.mk",
            "makeArgs": [
                // ...
                "-C exmpllogic/",
                "-f libexmpllogic.mk"
            ],
        },
```

**Comment by EricHripko** [comment]
Thank you for helping me out with this - really appreciate it 🙂 Will close this as resolved!
