### ISSUE TITLE
The preview version does not appear to be working properly

### ISSUE THREAD

**Issue by SeasClouds** [microsoft/vscode-makefile-tools#590]
I updated to the preview version (v0.10.5) and it is not working properly. didn't handle dry-run output, and didn't communicate with the cpp extension.
Normal after running `Makefile: Clean Configure`
![image](https://github.com/microsoft/vscode-makefile-tools/assets/44010231/91aba066-b96f-4219-98ed-2a516104bdcc)

**Comment by gcampbell-msft** [comment]
@SeasClouds Am I understanding you correctly that running `Makefile: Clean Configure` fixes the issue? If not, I'm not sure what you mean by "Normal after running `Makefile: Clean Configure`"

**Comment by SeasClouds** [comment]
@gcampbell-msft  Setting it to `true `still raises the issue. 
This issue should be caused by #573  submission. When `extension.getFullFeatureSet()` and `configuration.getConfigOnOpen()` return `true`, `make.cleanConfigure(make.TriggeredBy.cleanConfigOnOpen)` will not run. Is this your expectation

**Comment by gcampbell-msft** [comment]
@SeasClouds Ah, great catch, I'll fix this
