### ISSUE TITLE
[Loc] Tooltip not localized when hovering over “Configuration”

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-makefile-tools#598]
**More info:**
This issue is reproduced in other language environments as well

**Repro steps:**
1. Open VScode and open the “Makefile Tools Project Outline” page
2. Hove over the “Configuration: unset” line
3. Check that the tooltip is localized

**Expected result:**
The tooltip is localized

**Actual result:**
Tooltip not localized

**Configuration:**
![image](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/c1838412-11c9-4662-aa35-d8d3eadc0335)

**Comment by gcampbell-msft** [comment]
Fixed in #615

**Comment by Yingzi1234** [comment]
This issue has been fixed on latest version, you can get the details below. Thank you!

**ENV:**
Makefile tools version: v0.10.12(pre-release)
VSCode version: v1.91.1(user setup)
C/C++ version: v1.21.0(pre-release)

![image](https://github.com/user-attachments/assets/73a535b4-667e-4e6e-a30c-30f0c384334d)
