### ISSUE TITLE
[Loc] “Makefile: Focused Project Outline View” command comment line localized

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-makefile-tools#599]
**More info:**
This issue is reproduced in other language environments as well

**Repro steps:**
1. Open VScode 
2. Click F1 to run “Makefile” command
3. Check that the comment line below the “Makefile: Focus on Project Outline View” command is localized

**Expected result:**
The comment below the command should be in full English
 ![image](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/6f22c617-a29c-42d0-b4cc-573591970fa3)

**Actual result:**
The “Project Outline” in the comment below the command is localized
![image](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/90b26778-89b2-442d-80c3-3157c1b0df32)

**Comment by gcampbell-msft** [comment]
@Yingzi1234 We actually aren't providing the Focus on Project Outline view command, this is provided by VS Code, we only provide the view. Therefore, this bug should either be moved to the VS Code core team or we should close as "By design".

**Comment by Yingzi1234** [comment]
@gcampbell-msft Thank you for your update! We think this issue should be moved to the VS Code core team, but we don't know how to change the path of this issue, could you help us to change the path of this issue? Thank you in advance!
