### ISSUE TITLE
Build Failure on Win11 platform

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-makefile-tools#605]
**More info:**
1. This issue is only reproduced on Windows
2. This issue does not repro on VSCode version v1.89.1, so it is a VSCode regression bug
4. This issue is not reproduced Win10 platform

**Repro steps:**
1. Open VScode and clone this repo [https://github.com/remonbonbon/makefile-example.git](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fremonbonbon%2Fmakefile-example.git&data=05%7C02%7Cv-cathyzhang%40microsoft.com%7C47a77388299549041afb08dc91304fcd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638544883966793787%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=kGtfMaLi%2FHcY2FDwaQ1w0f%2Bdw%2BgX2cWC4EmNZuCGykk%3D&reserved=0)
2. Open the “Makefile Tools Project Outline” page
3. Set the build target to “all” and the launch target to “app” and save it
3. Click “build” button to build the current target
5. Check if the build was successful

**Expected result:**
Build will successfully(Win10 platform)
![image](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/4aa924e1-ff6f-49f2-b4ef-2d124f8252a6)

**Actual result:**
Build failed on Win11 OS
![issue2](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/05104415-1c9e-4b25-a9a8-32f3de3c9f18)

**Output log:**
[issue output log.txt](https://github.com/user-attachments/files/15921865/issue.output.log.txt)

**Comment by gcampbell-msft** [comment]
@Yingzi1234 Does this reproduce with any other projects? Or does it reproduce outside of the Makefile Tools extension? 

If we can confirm that this bug isn't tied to something in the Makefile Tools extension, then we should close this bug and open one directly on microsoft/vscode. Thanks

**Comment by Yingzi1234** [comment]
@gcampbell-msft This issue does not reproduced on latest Makefile tools version v0.10.16(pre-release), so we closed it. You can get the details below. Thank you!

"ENV:"
VSCode version: v1.91.1(system setup)
Makefile tools version: v0.10.16(pre-release)
C/C++ version: v1.21.2
Platform: Windows 11
![605](https://github.com/user-attachments/assets/8016c167-828a-45e8-9144-5a08a8eba94c)

**Comment by gcampbell-msft** [comment]
@Yingzi1234 Is there any additional information on why it was re-opened?

**Comment by Yingzi1234** [comment]
@gcampbell-msft Sorry for the confusion, we found that the problem recurs only on Makefile, not on CMake, so we re-opened it.

**In addition,** we found out that on top of two separate Win11 machines, there are two different results after the build, one will build successfully and one will fail, you can get the specific information from below:

**Win11-Success:**
![image](https://github.com/user-attachments/assets/6fdd9919-a5e7-4fae-a0af-43b504ad278b)


**Win11-Fail:**
![image](https://github.com/user-attachments/assets/e083932b-7db5-4487-b822-f5713e138796)

**Comment by Yingzi1234** [comment]
@gcampbell-msft Thank you for your reply! It looks like we're running into the same error as the one in this issue, and we'll keep tracking it until it's fixed.

Error message:
```
g++ -O2 -Wall -I./include   -c -o src/main.o src/main.cpp
g++ -O2 -Wall -I./include   -c -o src/mod/mod.o src/mod/mod.cpp
g++ -lm -o app src/main.o src/mod/mod.o
**collect2.exe: error: ld returned 116 exit status**
make: *** [Makefile:16: app] Error 1

 *  The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command & 'make.exe' 'all'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it
```

**Comment by gcampbell-msft** [comment]
@Yingzi1234 Lastly, does this reproduce on the command-line without the extension? It sounds like it does based on the most recent comment. In which case, I think this issue can be closed as external. I'll close now but please reopen if this isn't the case.
