### ISSUE TITLE
[Loc] Makefile tools UI not localized on Linux for CHS and CHT 

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode-makefile-tools#609]
**Environment**:
[VSCode 1.90.1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2F&data=05%7C02%7Cv-phta%40microsoft.com%7C8a22e1689c32475b2bb808dc951b3b30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638549191526247366%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=wHeEZXxd2PJhz6owZnY3pwAMx%2BbTO3CH%2F%2Bq%2BTP%2BFYYk%3D&reserved=0) + Makefile Tools v0.10.9(pre-release)

**More info**:
1)	Repro Language: CHS, CHT
2)	Not repro language: other 11 languages(JPN, KOR, ESN, RUS, FRA, DEU, ITA, PLK, PTB, CSY, TRK)
3)	Repro platform: Linux

**Repro steps:**
1. Open VScode on Linux, and change the display language to CHS or CHT
2. Open setting page and input “Makefile”, check the setting's description localization status
3. Click F1 to open command palette and input “Makefile”, check the command localization status
4. Click sidebar for Makefile and check the localization status for “Makefile: Project Outline" window 

**Expected result:**
‘Makefile tools UI localized on Linux for CHS and CHT 
(Localized for CHS and CHT on Windows and Mac, localized for other languages on Linux)

Outline_CHS_Windows:
![image](https://github.com/microsoft/vscode-makefile-tools/assets/37648162/7a302458-19d2-4ecb-b8da-d198b921ba68)

Settings and Command_JPN _Linux:
Note: The new added description for  "makefile.panel.visibility" not localized on v0.10.10(pre-release)
As [The "Makefile> Panel: Visibility" setting has no description in the Settings UI · Issue #603 · microsoft/vscode-makefile-tools (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode-makefile-tools%2Fissues%2F603&data=05%7C02%7Cv-phta%40microsoft.com%7C8a22e1689c32475b2bb808dc951b3b30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638549191526336758%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=mg8R9UkTAM7oLEH69OLSdTI%2FOQzqRzhikTNlhXa7oWM%3D&reserved=0) just fixed on v0.10.10(pre-release).
![image](https://github.com/microsoft/vscode-makefile-tools/assets/37648162/e862004b-a21a-4850-8baf-49891fde1664)

**Actual result:**
‘Makefile tools UI not localized on Linux for CHS and CHT

Outline_CHS _Linux:
![image](https://github.com/microsoft/vscode-makefile-tools/assets/37648162/5342f570-7914-4b24-b077-865482f50e88)

Settings and Command_CHS _Linux: Just one command “Makefile: Focus on Project Outline View” localized
![image](https://github.com/microsoft/vscode-makefile-tools/assets/37648162/17423353-d07b-4c23-827d-b7fed5cc36dc)

![image](https://github.com/microsoft/vscode-makefile-tools/assets/37648162/54e22cf3-d3f4-49ef-ad8c-5861718254fa)

**Comment by gcampbell-msft** [comment]
@PhoebeTf When testing on linux, is the VS Code language setting set to CHS?

**Comment by PhoebeTf** [comment]
@gcampbell-msft Yes, when testing on linux, changed the VS Code language setting to CHS/CHT, you can check this in the issue repro step part.

**Comment by gcampbell-msft** [comment]
@PhoebeTf Could you test out this vsix and see if the issue still happens? 
[makefile-tools.zip](https://github.com/user-attachments/files/16196431/makefile-tools.zip)

You'll have to modify the extension from `.zip` to `.vsix` and then manually install the extension. Thanks!

**Comment by PhoebeTf** [comment]
@gcampbell-msft Makefile Tools UI still not localized with the extension installed with above one you shared.
![NotLoc_Linux](https://github.com/user-attachments/assets/1c188d43-f200-40d0-991d-ca254ed445a5)

**Comment by gcampbell-msft** [comment]
Ah, I think I've figured it out, could you test this? 
[makefile-tools.zip](https://github.com/user-attachments/files/16255590/makefile-tools.zip)

**Comment by PhoebeTf** [comment]
@gcampbell-msft It seems UI still not localized on Linux with the new version Makefile tools extension that was shared by you.
![NotLoc_Linux_0717](https://github.com/user-attachments/assets/739754ec-2b35-43d5-9579-13b5553b68d9)

**Comment by gcampbell-msft** [comment]
I just confirmed this to be fixed in the most recent pre-release v0.10.14

**Comment by PhoebeTf** [comment]
Verified with Makefile Tools v0.10.21(pre-release), this issue has been fixed.
![image](https://github.com/user-attachments/assets/92b79d09-b24f-46cf-a2ad-6e468005aafa)
