### ISSUE TITLE
[Loc] Inconsistent translation for "dry-run" in CHS

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode-makefile-tools#612]
**Environment:**
[VSCode 1.90.1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2F&data=05%7C02%7Cv-phta%40microsoft.com%7C8a22e1689c32475b2bb808dc951b3b30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638549191526247366%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=wHeEZXxd2PJhz6owZnY3pwAMx%2BbTO3CH%2F%2Bq%2BTP%2BFYYk%3D&reserved=0) + Makefile Tools v0.10.9(pre-release)

**More info:**
Repro Language: CHS
Repro platform: Windows, Linux, Mac

**Repro steps:**
1. Open VScode and change the display language to CHS
2. Clone the makefile project (such as: https://github.com/remonbonbon/makefile-example) and open it in VSCode
3. Click F1 to open command palette and input “Makefile: configure”, check the popup dialog localization status
4. Open setting page and input “Makefile”, check the setting's description localization status for "makefile.Build Log", 
"makefile.configrationCachePath", "makefile.dryrunSwitches"

**Expected result:**
"dry-run" with consistent translation and translated to “试运行” in CHS
makefile.Build Log: 
![image](https://github.com/microsoft/vscode-makefile-tools/assets/37648162/09db7c1b-6b60-4868-8772-2d59c6c8eb19)

makefile.configrationCachePath: 
![image](https://github.com/microsoft/vscode-makefile-tools/assets/37648162/91397b0d-4aea-4344-8e0f-e00e2d0fe0ff)

**Actual result:**
"dry-run" translated to “干运行” in the pop up dialog and “makefile.dryrunSwitches” description in CHS

![image](https://github.com/microsoft/vscode-makefile-tools/assets/37648162/0306f285-e491-4969-b9d4-ef688ccab8f1)

makefile.dryrunSwitches: 
![image](https://github.com/microsoft/vscode-makefile-tools/assets/37648162/e96b1bb8-8f81-4bb4-b30b-a0ab7bcf1d74)

**Comment by gcampbell-msft** [comment]
Created bug here: https://ceapex.visualstudio.com/CEINTL/_workitems/edit/981826

**Comment by gcampbell-msft** [comment]
Fixed in #615

**Comment by PhoebeTf** [comment]
@gcampbell-msft Verified with Makefile Tools v0.10.12, "dry-run" has been translated to “试运行” for "makefile.dryrunSwitches", while still translated to “干运行” in the pop up dialog, could you help to confirm do I need reactive this issue? Or create a new issue?
![image](https://github.com/user-attachments/assets/9ccac5df-49b2-45c2-ab26-af3e461fae7e)

**Comment by gcampbell-msft** [comment]
I've reactivated this bug: https://ceapex.visualstudio.com/CEINTL/_workitems/edit/981826

**Comment by gcampbell-msft** [comment]
Fixed with #621

**Comment by PhoebeTf** [comment]
Verified with Makefile Tools v0.10.21(pre-release), "dry-run" has been translated to “试运行” in the pop up dialog
![image](https://github.com/user-attachments/assets/fba857b1-4ecd-4fd3-9b9b-3662738b63fb)
