### ISSUE TITLE
“$” appeared in Makefile tools pop up dialog when build project

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode-makefile-tools#613]
**Environment:**
[VSCode 1.90.1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2F&data=05%7C02%7Cv-phta%40microsoft.com%7C8a22e1689c32475b2bb808dc951b3b30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638549191526247366%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=wHeEZXxd2PJhz6owZnY3pwAMx%2BbTO3CH%2F%2Bq%2BTP%2BFYYk%3D&reserved=0) + Makefile Tools v0.10.9(pre-release)

**More info:**
Repro Language: ENU and all loc
Repro platform: Windows, Linux, Mac

**Repro steps:**
1.	Clone the repository [https://github.com/remonbonbon/makefile-example.git](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fremonbonbon%2Fmakefile-example.git&data=05%7C02%7Cv-phta%40microsoft.com%7C8a22e1689c32475b2bb808dc951b3b30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638549191526342816%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ufpp5QbTbkOTfRIFslqk%2Fy6POktcB6k7y70ZI6qzBWU%3D&reserved=0) 
2.	Open the project with VSCode 
3.	Navigate to “Makefile: project outline” window
4.	Click the icon for “Makefile: Build the current target”
5.	Check the string in popup dialog

**Expected result:**
Without “$” in Makefile tools pop up dialog

**Actual result:**
“$” appeared in Makefile tools pop up dialog

ENU string: Building $ the current makefile configuration $
![image](https://github.com/microsoft/vscode-makefile-tools/assets/37648162/760a9854-f8c3-4ab1-94dd-8112738703d6)

**Comment by Yingzi1234** [comment]
@gcampbell-msft @PhoebeTf This issue has been fixed on latest Makefile Tools version v0.10.17(pre-releaese), you can get the details below. Thank you!
![image](https://github.com/user-attachments/assets/f5565131-52dc-401d-a31a-f2a7f0dc60c1)
