### ISSUE TITLE
Make configuring from cache truly async

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#62]
Configuring from cache is in general fast but for large projects it's still not instantaneous and when verbose logging is enabled is can last a while. Make this functionality truly async as well.

**Comment by gcampbell-msft** [comment]
I think there are other issues that track making things async, closing.

**Comment by andreeis** [comment]
Oh right, https://github.com/microsoft/vscode-makefile-tools/issues/105.
