### ISSUE TITLE
"Unset" is not enclosed in square brackets

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-makefile-tools#620]
**More info:**
1. This issue is reproduced on Windows, Linux, and Mac platforms
2. This issue does not reproduced on version 0.10.10, so it is a regression issue

**Repro steps:**
1. Install the makefile extension and open VSCode
2. Open the “Makefile Project Outline” page 
3. Check that the "Build Log: [Unset]" line is displayed correctly 

**Expected result:**
"Unset" should be enclosed in square brackets

**Makefle tools version: v0.10.10(pre-release)**
![image](https://github.com/user-attachments/assets/81e9f265-6929-4045-b5b7-206a050a4a11)

**Actual result:**
"Unset" is not enclosed in square brackets

**Makefile tools version: v0.10.12(pre-release)**
![image](https://github.com/user-attachments/assets/d917f671-663a-49a7-8330-6d768a83a466)

**Comment by gcampbell-msft** [comment]
Fixed with #618

**Comment by Yingzi1234** [comment]
This issue has been fixed on latest Makefile tools version v0.10.16(pre-release), you can get the details below. Thank you!
![image](https://github.com/user-attachments/assets/4d297a80-e407-4403-9cf4-11a0d260aa84)
