### ISSUE TITLE
[Local] String “The pre-configure succeeded” and “The post-configure succeeded” not localized in Makefile tools output window

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-makefile-tools#636]
**More info:**
**1. This issue is reproduced on v0.9.10(release), so it is not a regression issue**
2. Repro Language: all loc
3. Repro platform: Windows, Linux, Mac
 
**Repro steps:**
1. Open VScode and change the display language to CHS
2. Open VSCode and clone the repository, such as:  [https://github.com/remonbonbon/makefile-example.git](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fremonbonbon%2Fmakefile-example.git&data=05%7C02%7Cv-cathyzhang%40microsoft.com%7C9325a79d39494e46441f08dcb62d301f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638585552453966147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=LMiNsw6mep4Z470UnjjsKICrKD%2BYTPncjHTxQtqNn4o%3D&reserved=0)
3. Create a pre-configure file or post-configure, such as: “preConfigureScript.bat”
4. Copy the contents: ECHO “PRECONFIGURE” %~1 to this file
5. Copy this file's path to the "Makefile: Pre Configrue Script” settings
6. Click F1 to run command "Makefile: Pre-configure" 
7. Check the output window

**Expected result:**
Makefile output log all localized

**Actual result:**
String “The pre-configure succeeded” and “The post-configure succeeded” not localized in Makefile tools output window

**pre-configure:** 
![image](https://github.com/user-attachments/assets/03548e81-7aa4-40bd-a775-54a450d8d7ba)

post-configure:
![image](https://github.com/user-attachments/assets/40315fc5-32b8-4163-9de2-b229b20d1c31)

**Comment by gcampbell-msft** [comment]
Fixed by #634

**Comment by Yingzi1234** [comment]
@gcampbell-msft I apologize that this issue has not been fully resolved, so I've turned it back on. Only “The pre-conigure succeeded” is translated, but “The post-configure succeded” has not been translated yet. You can get the details below. Thank you!

ENV:
Makefile tools verison: v0.11.6(pre-release)
vscode verison: 1.92.2

Post-configure
![image](https://github.com/user-attachments/assets/ce5217ab-75dd-4b4e-a0fc-a1de0a7bb624)

Pre-configure
![image](https://github.com/user-attachments/assets/136cbca8-3305-4859-83a8-bbb2f44d90da)

**Comment by Yingzi1234** [comment]
@gcampbell-msft I'm sorry to say that this issue still hasn't been resolved by this PR [643](https://github.com/microsoft/vscode-makefile-tools/pull/643) , so I've turned it back on. “Post-configuration success” has not been translated yet. You can get the details below. Thanks!
![image](https://github.com/user-attachments/assets/c1630077-85e1-4b77-9883-cf4d5430864f)

**Comment by gcampbell-msft** [comment]
Just tested in pre-release, this is fixed in the most recent version 👍

**Comment by Yingzi1234** [comment]
@gcampbell-msft Thank you very much for reconfirming, this issue has been fixed on latest Makefile Tools version 0.12.4(pre-release), you can get the details below. Thank you!
![Image](https://github.com/user-attachments/assets/718e00d4-976a-4f53-80fe-1994777efc8a)
