### ISSUE TITLE
[Local] String “Could not find pre-configure script” not localized in Makefile tools popup dialog

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-makefile-tools#637]
**More info:**
**1. This issue is reproduced on v0.9.10(release), so it is not a regression issue**
2. Repro Language: all loc
3. Repro platform: Windows, Linux, Mac
4. This issue is only reproduced with pre-configure

**Repro steps:**
1. Open VScode and change the display language to CHS
2. Open VSCode and clone the repository, such as:  [https://github.com/remonbonbon/makefile-example.git](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fremonbonbon%2Fmakefile-example.git&data=05%7C02%7Cv-cathyzhang%40microsoft.com%7C9325a79d39494e46441f08dcb62d301f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638585552453974187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=GJyfOK0zd9FeaDx6DwvW%2BzJ92XRYPtTwk2a4ZL45FqU%3D&reserved=0)
3. Change the value of "Makefile: Pre Configrue Script” settings to “test”
4. Click F1 to run command "Makefile: Pre-configure" 
5. Check the popup dialog

**Expected result:**
Makefile tools popup dialogues all localized
 
**Actual result:**
String “Could not find pre-configure script” not localized in Makefile tools popup dialog

**pre-configure:**     
 ![image](https://github.com/user-attachments/assets/3574ac49-7884-42ae-8519-3cd101f429d7)

**Post-configure:**
![image](https://github.com/user-attachments/assets/af39b64d-7789-40e8-8817-6a6c029e74b7)

**Comment by gcampbell-msft** [comment]
Fixed by #634
