### ISSUE TITLE
Add non-intrusive warning for source files without found configuration, but don't warn for dependencies of such file.

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#64]
Here is some additional feedback: in large projects like this, it is common for not all source files to be compiled. With this extension, if a source file is not compiled, then there is no configuration for it, so IntelliSense will likely give all sorts of #include errors. It would be nice if there was a way to provide a non-intrusive warning to the user when they open a file for which there is no configuration for. I do see that there is a message in the output log that looks like "Configuration for file /.../.../... was not found. CppTools will set a default configuration." So perhaps whatever branch in the code prints this message could also be used to provide this warning. Unfortunately though, it might not be this simple. When I open a header file that was #include'ed during the kernel build, this same message also gets printed to the output log. This makes sense, as header files don't get passed to the compiler as a source file, so this extension doesn't know about them. 

Maybe it would be possible to generate a list of dependencies for each source file during the configuration process, and then not warn when opening one of these dependencies? This could be done as follows (I'll use the source file fec_main.c in my project as an example.)

fec_main.c gets compiled with this enormous command:

arm-linux-gnueabihf-gcc -Wp,-MD,drivers/net/ethernet/freescale/.fec_main.o.d -nostdinc 
-isystem /usr/lib/gcc-cross/arm-linux-gnueabihf/7/include -I./arch/arm/include 
-Iarch/arm/include/generated/uapi -Iarch/arm/include/generated 
-Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi 
-Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian 
-fdebug-prefix-map==. -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing 
-fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE 
-fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fno-ipa-sra 
-mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a 
-msoft-float -Uarm -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 
-Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable 
-fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g 
-Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack 
-Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -fdebug-prefix-map==. 
-D__CHECK_ENDIAN__ -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(fec_main)" 
-D"KBUILD_MODNAME=KBUILD_STR(fec)" -c -o drivers/net/ethernet/freescale/.tmp_fec_main.o 
drivers/net/ethernet/freescale/fec_main.c

This command builds the object file and creates a dependency file at ".fec_main.o.d". But when building the kernel, this dependency file is deleted towards the end of the build process. Even if this dependency file was not deleted, it would not be good to rely upon its existence because not all build systems will generate these dependency files. To generate this dependency file, I'd recommend the following procedure:

1.	Remove all "-M*" options from the gcc command. See https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html and Ctrl+F for "-M" to see the various -M* options. (The command above does not have a -M* parameter directly, but it could in general. The command above instead uses the -Wp option; see the next step in this procedure.)
2.	If the gcc command contains a "-Wp" option (like the command above does), search within this string for the same "-M*" options and remove them. -Wp is used to pass options directly to the pre-processor. If there are no options remaining in the comma-separated list after -Wp, then the -Wp option must be removed entirely. (You can't use -Wp with an empty list of options. On my system, just using "-Wp" is an error, and "-Wp," causes gcc to hang.)
3.	Remove the -o option from the gcc command, if one exists.
4.	Add "-M" to the gcc parameters.
5.	Run the resulting command, and the dependencies should be output to stdout. The extension could capture this output, or direct it to a file using the "-MF my_dependencies.d" option after the "-M" option from step 4.
Any files that appear in this dependency list should not cause a warning when opened.

Here is the resulting command after following the above procedure:

arm-linux-gnueabihf-gcc -M -nostdinc 
-isystem /usr/lib/gcc-cross/arm-linux-gnueabihf/7/include -I./arch/arm/include 
-Iarch/arm/include/generated/uapi -Iarch/arm/include/generated 
-Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi 
-Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian 
-fdebug-prefix-map==. -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing 
-fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE 
-fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fno-ipa-sra 
-mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a 
-msoft-float -Uarm -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 
-Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable 
-fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g 
-Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack 
-Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -fdebug-prefix-map==. 
-D__CHECK_ENDIAN__ -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(fec_main)" 
-D"KBUILD_MODNAME=KBUILD_STR(fec)" -c 
drivers/net/ethernet/freescale/fec_main.c

**Comment by gcampbell-msft** [comment]
Suggest to close due to age of ticket.
