### ISSUE TITLE
Semicolon in single quotes causes dryruntarget to fail

### ISSUE THREAD

**Issue by wkdzzb** [microsoft/vscode-makefile-tools#671]
makefile-tools version：0.11.13

dryrun.log
```shell
...
set -e;  echo '  RELOCS  arch/x86/boot/compressed/vmlinux.relocs';  arch/x86/tools/relocs vmlinux > arch/x86/boot/compressed/vmlinux.relocs;arch/x86/tools/relocs --abs-relocs vmlinux; printf '%s\n' 'cmd_arch/x86/boot/compressed/vmlinux.relocs := arch/x86/tools/relocs vmlinux > arch/x86/boot/compressed/vmlinux.relocs;arch/x86/tools/relocs --abs-relocs vmlinux' > arch/x86/boot/compressed/.vmlinux.relocs.cmd
...
```

Makefile tools output
```
Error running the compiler args parser script /root/.vscode-server/extensions/ms-vscode.makefile-tools-0.11.13/assets/parseCompilerArgs.sh for regions (--abs-relocs vmlinux' > arch/x86/boot/compressed/.vmlinux.relocs.cmd): /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
/bin/bash: -c: line 2: syntax error: unexpected end of file
```

I found the real reason is the function preprocessDryRunOutput.

```js
async function preprocessDryRunOutput(cancel, dryRunOutputStr, statusCallback) {
...
    preprocessTasks.push(function () {
        preprocessedDryRunOutputStr = preprocessedDryRunOutputStr.replace(/ && /g, "\n");
    });
    // Split multiple commands concatenated by ";"
    preprocessTasks.push(function () {
        preprocessedDryRunOutputStr = preprocessedDryRunOutputStr.replace(/;/g, "\n");
    });
...
}
```
the function preprocessDryRunOutput replaces ';' with '\n',but in some shell cmd, like this
```shell
echo 'echo 123;echo 456' > ./tmp
```
replace ';' with '\n' 
```shell
echo 'echo 123
echo 456' > ./tmp
```
it will cause an error

**Comment by Amy-Li03** [comment]
Hi @wkdzzb, thanks for reporting issue.
We try to repro your issue on our end with latest Makefile Tools v0.12.10 (pre-release), following screenshot is the test result, could you please confirm whether this is your issue?
Thanks for help us build a better Makefile Tools!
![Image](https://github.com/user-attachments/assets/6664de6c-d39b-438b-adf2-0f4acf16ec55)

**Comment by wkdzzb** [comment]
I wrote a makefile and appended these, and it repeats
```makefile
$(target):$(obj)
	$(GCC) $(C_FLAGS) $^ $(head) -o $@
	make: Entering directory '/root/code/kernel-5.10.0-60.18.0.50.oe2203'
	gcc   -o arch/x86/tools/relocs arch/x86/tools/relocs_32.o arch/x86/tools/relocs_64.o arch/x86/tools/relocs_common.o;
	echo 'echo 123; arch/x86/tools/relocs --abs-relocs vmlinux' > ./tmp
```

**Comment by gcampbell-msft** [comment]
@wkdzzb @Amy-Li03 Could you confirm whether this is a new / regression issue in the most recent versions? Based on @wkdzzb's information and code link, it's not, but I want to confirm. Thanks!

**Comment by gcampbell-msft** [comment]
@wkdzzb Also, is this currently blocking you? Or is this something that you're able to workaround by slightly modifying your makefile?

**Comment by wkdzzb** [comment]
> [@wkdzzb](https://github.com/wkdzzb) [@Amy-Li03](https://github.com/Amy-Li03) Could you confirm whether this is a new / regression issue in the most recent versions? Based on [@wkdzzb](https://github.com/wkdzzb)'s information and code link, it's not, but I want to confirm. Thanks!

I can confirm that this is not a new or regression issue in the latest versions. I tested all versions of makefile tools from 0.8 to 0.12, and this issue exists in all of them. Additionally, I tried using double quotes, but the issue still occurs.

**Comment by wkdzzb** [comment]
This is not blocking me; however, it does cause issues with VSCode's hints and code completion, resulting in many errors being reported. The makefile is also difficult to modify since it is the kernel's makefile.

**Comment by wkdzzb** [comment]
I think replacing a semicolon  with a newline inside single or double quotes is problematic, as it can break the original shell commands. However, replacing a semicolon with a newline outside of quotes should not be an issue.

**Comment by gcampbell-msft** [comment]
@wkdzzb Could you please test out the vsix that is linked here: https://github.com/microsoft/vscode-makefile-tools/pull/678?

You'll need to download the .zip and change the extension to .vsix and then you can install it manually into vscode from the extensions pane. Thanks!
