### ISSUE TITLE
Debug doesn't work with binaryArgs

### ISSUE THREAD

**Issue by GulgDev** [microsoft/vscode-makefile-tools#672]
When I build my C project and debug it with GDB externally, it work very well. It also works with the VSCode extension, however, when I add binaryArgs to my configuration:
```json
"makefile.launchConfigurations": [
	{
		"cwd": "D:\\MyProject",
		"binaryPath": "D:\\MyProject\\build\\program.exe",
		"binaryArgs": ["D:\\MyProject\\file.txt"]
	}
]
```
It stops working and GDB just crashes.

**Comment by GulgDev** [comment]
I'm sorry, it turns out that there was a problem on my end.

**Comment by Yingzi1234** [comment]
@GulgDev I'm glad that it got resolved, thanks!
