### ISSUE TITLE
More advanced "phony" analysis for targets

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-makefile-tools#68]
For preview 1, we are fixing https://github.com/microsoft/vscode-makefile-tools/issues/8 by adding a new setting (list only phony targets defaulting to false) and by printing only the targets that were manually marked ".PHONY" by the developer.
In future it would be nice to include in that fix a more advanced analysis of how phony is a target that was not defined so by the user. Like evaluate if the target name represents a file on disk or not.

Phony definition: 
A phony target is one that is not really the name of a file; rather it is just a name for a recipe to be executed when you make an explicit request. There are two reasons to use a phony target: to avoid a conflict with a file of the same name, and to improve performance.

**Comment by gcampbell-msft** [comment]
This is a very old ticket, and we may have fixed this already. Putting suggest-to-close until further feedback and discussion with @andreeis
