### ISSUE TITLE
Defines are not detected

### ISSUE THREAD

**Issue by KrestenHelstrup** [microsoft/vscode-makefile-tools#84]
Hi guys
I'm under the impression that this extension should find defines from the makefile, but I can't get it working - however, everything else seems to be working.
Do I need to configure anything to get "-Dxxx" from cflags? Are there any way to see what is currently extracted from the makefile?
Thanks in advance

**Comment by andreeis** [comment]
Sure, we'll figure out how to have all the defines (and includes and other things tied to compiler flags) seen by the extension.
You don't need makePath if make is in the path of the environment you open VSCode from.
You don't need makefilePath if the makefile is in the root folder of your project.

Set makefile.loggingLevel to debug, and makefile.extensionLog to ".vscode/extension.log", reload the project and share with us the contents of .vscode/extension.log and .vscode/dryrun.log.

**Comment by KrestenHelstrup** [comment]
I have attached the files requested plus my settings.json. I observe two issues, defines from the Makefile is not detected and IntelliSense can't find includes from GCC.

[dryrun.log](https://github.com/microsoft/vscode-makefile-tools/files/5847894/dryrun.log)
[extension.log](https://github.com/microsoft/vscode-makefile-tools/files/5847893/extension.log)
[settings.json.txt](https://github.com/microsoft/vscode-makefile-tools/files/5847896/settings.json.txt)

**Comment by andreeis** [comment]
I see the problem and we'll fix it before our next release. Our compiler path parser is confused by the different slashes and inner quotes: 'C:\ARMTC\ARMGCC'/bin/arm-none-eabi-gcc.

As a workaround until you get the fix, can you convince your make to produce a text log without the unnecessary ' characters and with consistent forward or backward slashes? Or a text log without any path associated to arm-none-eabi-gcc and you make sure it's on the path in the terminal you open VSCode from?
Or, create a full build (make sure it contains compilation commands for all the source files you're interested in), save it's build log somewhere, change or remove the paths to arm-none-eabi-gcc and reference the saved output via makefile.buildLog setting. In this case, the extension will not invoke make --dry-run anymore and will just parse everything that is needed from that file.

Are you on MinGW? Just for convenience, for expanding our testing coverage and for making it easier to provide you with solutions to problems, do you happen to work on a public repository that we can enlist on?

**Comment by KrestenHelstrup** [comment]
Thank you for the fast feedback.
Does it make any difference if I will stick to '/' or '\' ?
I will try to update the makefile to omit the ' characters.
I'm not using MinGW - Just a windows installation with arm-gcc toolchain and vscode installed.
At the moment I don't have the software on any public repository but if your first suggestions doesn't solve my issue I could make a repository.

**Comment by KrestenHelstrup** [comment]
Hi again
I think omitting the ' characters solved the initial issue - Now I see my defines in the configurationCache.log:
"configuration":{"defines":["EFM32G890F128","STARTUP_MODE=(SystemModes_t)NORMAL_MODE","DEBUG"]
However, it seems like the IntelliSense still doesn't detect those defines - #ifdef STARTUP_MODE resolves to false.
Do I need additional steps to get the IntelliSense running ?

Lastly: The gcc includes, like stdbool.h, are not auto detected - Do I need to add those to the makefile includes?

**Comment by andreeis** [comment]
Oh, let's see what output channel or makefile.extensionLog show about those defines, can you attach again extension.log like you did before? It should work already, I can't think of any extra step.

You don't need to add system includes, they should be automatically detected from compiler path information. Time to attach more files :). The output channel for C/Cpp and the output channel for C/Cpp Diagnostics. These 2 output channels after you open a source file where you see the squiggles. They would apply to that source file only. If you want us to have a look at 2 source files (one with header squiggle one with define squiggle) we need 2 sets of these 2 output channels.

Our testing base for windows is not as extensive as we'd like for now. Any real world project would help actually :). We'd love a windows repository if you could make one. And we'd also fix all your squiggles without exchanging so much investigation effort :).

**Comment by KrestenHelstrup** [comment]
I managed to get it working after running "Reset the makefile tools extension".
Thank you very much for your help. I will try to setup a repo for embedded C development on Windows - Will let you know when it's ready.
