### ISSUE TITLE
Additional settings

### ISSUE THREAD

**Issue by KrestenHelstrup** [microsoft/vscode-makefile-tools#88]
I have a few suggestions for new settings. Maybe some of these already exist but I haven't found them yet.
At least I would very much like to have all of them.
1) A force build setting to ensure that the build is up to date before running launch/debug command.
2) A name setting on the launch configurations so it easier to switch between different configurations.
3) Point the debug from makefile extension to an existing launch.json configuration - in my case a launch of cortex-debug extension.
4) Point the default build task (executed by ctrl + shift + b) to build/rebuild via make extension.

Thanks in advance.

**Comment by andreeis** [comment]
Thank you for the ideas, keep them coming :).

1. Will do
2. Will do. We don't have a short name setting yet but there is a long name composed by [CWD]>[BINARY]([ARG1],[ARG2],[ARG3[,...) which you can select with the command makefile.setLaunchConfiguration via the pallette or the button in the left side panel. When the name is too long to fit, you can mouse over and see it in the tooltip.
3. This is done, I explained in the other report you created https://github.com/microsoft/vscode-makefile-tools/issues/87#issuecomment-766866200.
4. Will think about it.

**Comment by KrestenHelstrup** [comment]
As you can see from the picture below the long name becomes a bit fucked.
![launchTargets](https://user-images.githubusercontent.com/74759135/105724636-58ea1b00-5f28-11eb-9b91-a627ee81707e.PNG)

**Comment by andreeis** [comment]
That path is interesting. You have the latest Makefile Tools 0.1.3, right? We fixed some bugs that looked like that.
You are not setting makefile.ignoreDirectoryCommands to false in settings, right?
I'd like to see the dryrun output and the .vscode/extension.log to see if there's anything else we missed.

**Comment by KrestenHelstrup** [comment]
Yes - I'm using 0.1.3.
No, I don't set makefile.ignoreDirectoryCommands - I have added my full settings.json for reference.
[dryrun.log](https://github.com/microsoft/vscode-makefile-tools/files/5867604/dryrun.log)
[extension.log](https://github.com/microsoft/vscode-makefile-tools/files/5867605/extension.log)
[settings.json.log](https://github.com/microsoft/vscode-makefile-tools/files/5867610/settings.json.log)

Regardin 3)
What I meant was - When I click this icon
![Debug](https://user-images.githubusercontent.com/74759135/105727254-2ee62800-5f2b-11eb-94aa-b2c3063a504f.PNG)
I would like it to run an already existing configuration from launch.json.

**Comment by andreeis** [comment]
Oh, the same happens for the CMake Tools extension, the launch.json is not yet consumed by the Makefile Tools extension. The Makefile debug feature creates a new simple launch.json on the fly and targets the users that would like to skip the step of authoring a launch.json file.

Launch.json is read only if you debug via "F5" (or the Debugger debug command, not the Makefile debug command). Launch.json can ask Makefile Tools things via those variables but otherwise the debugging is controlled by CppTools and Debugger extensions.

We would like to unify the two scenarios but that won't happen soon.
It looks that you have a well setup launch.json. In this case we recommend you debug with F5.

**Comment by KrestenHelstrup** [comment]
Okay - Thanks for the info.

**Comment by andreeis** [comment]
Triaging to 0.1.4 for bullet 1 (setting for build before debug/run). Will create later new reports from the rest of the suggestions.

**Comment by andreeis** [comment]
You can install the VSIX built from the last merged PR here: https://github.com/microsoft/vscode-makefile-tools/actions/runs/537903962#artifacts. We hope your experience with Makefile Tools extension will be much improved. Let us know if you find any other issues. We might be able to address them before our next week release.
